"""Type stubs for tensorflow.python.ops.ctc_ops - provided by LegacyKerasPatch."""

from typing import Any

def ctc_beam_search_decoder_v2(inputs: Any, sequence_length: Any, beam_width: Any = ..., top_paths: Any = ...) -> Any: ...
def ctc_greedy_decoder(inputs: Any, sequence_length: Any, merge_repeated: Any = ..., blank_index: Any = ...) -> Any: ...
def ctc_loss_v2(labels: Any, logits: Any, label_length: Any, logit_length: Any, logits_time_major: Any = ..., unique: Any = ..., blank_index: Any = ..., name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
