"""Type stubs for tensorflow.python.ops.nn_impl - provided by LegacyKerasPatch."""

from typing import Any

# Normalization
def batch_normalization(x: Any, mean: Any, variance: Any, offset: Any, scale: Any, variance_epsilon: Any, name: Any = ...) -> Any: ...
def l2_normalize_v2(x: Any, axis: Any = ..., epsilon: Any = ..., dim: Any = ..., name: Any = ...) -> Any: ...
def moments_v2(x: Any, axes: Any, shift: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...

# Activations
def swish(x: Any) -> Any: ...
def sigmoid(x: Any, name: Any = ...) -> Any: ...
def silu(features: Any, beta: Any = ...) -> Any: ...
def log_sigmoid(x: Any, name: Any = ...) -> Any: ...

# Loss functions
def sigmoid_cross_entropy_with_logits_v2(labels: Any, logits: Any, name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
