"""Type stubs for tensorflow.python.ops.nn_ops - provided by LegacyKerasPatch."""

from typing import Any

# Pooling operations
def avg_pool_v2(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def avg_pool1d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def avg_pool2d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def avg_pool3d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool_v2(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool1d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool2d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool3d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...

# Convolution operations
def conv1d_v2(input: Any, filters: Any, stride: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv1d_transpose(input: Any, filters: Any, output_shape: Any, strides: Any, padding: Any = ..., data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv2d_v2(input: Any, filters: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv2d_transpose_v2(input: Any, filters: Any, output_shape: Any, strides: Any, padding: Any = ..., data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv3d_v2(input: Any, filters: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv3d_transpose_v2(input: Any, filters: Any, output_shape: Any, strides: Any, padding: Any = ..., data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def depthwise_conv2d_v2(input: Any, filter: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def separable_conv2d(input: Any, depthwise_filter: Any, pointwise_filter: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...

# Bias
def bias_add(value: Any, bias: Any, data_format: Any = ..., name: Any = ...) -> Any: ...

# Activations
def relu(features: Any, name: Any = ...) -> Any: ...
def relu6(features: Any, name: Any = ...) -> Any: ...
def leaky_relu(features: Any, alpha: Any = ..., name: Any = ...) -> Any: ...
def elu(features: Any, name: Any = ...) -> Any: ...
def selu(features: Any, name: Any = ...) -> Any: ...
def gelu(features: Any, approximate: Any = ..., name: Any = ...) -> Any: ...
def softmax_v2(logits: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def log_softmax_v2(logits: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def softplus(features: Any, name: Any = ...) -> Any: ...
def softsign(features: Any, name: Any = ...) -> Any: ...

# Loss functions
def softmax_cross_entropy_with_logits_v2(labels: Any, logits: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def sparse_softmax_cross_entropy_with_logits(labels: Any, logits: Any, name: Any = ...) -> Any: ...

# Dropout
def dropout_v2(x: Any, rate: Any = ..., noise_shape: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
