from typing import Any


class SeedGenerator: ...

def beta(*args: Any, **kwargs: Any) -> Any: ...
def binomial(*args: Any, **kwargs: Any) -> Any: ...
def categorical(*args: Any, **kwargs: Any) -> Any: ...
def dropout(*args: Any, **kwargs: Any) -> Any: ...
def gamma(*args: Any, **kwargs: Any) -> Any: ...
def normal(*args: Any, **kwargs: Any) -> Any: ...
def randint(*args: Any, **kwargs: Any) -> Any: ...
def shuffle(*args: Any, **kwargs: Any) -> Any: ...
def truncated_normal(*args: Any, **kwargs: Any) -> Any: ...
def uniform(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
