"""Type stubs for keras.random module - provided by LegacyKerasPatch."""

from typing import Any

from legacy_keras_patch.random import SeedGenerator as SeedGenerator

def normal(shape: Any, mean: float = ..., stddev: float = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def uniform(shape: Any, minval: float = ..., maxval: float = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def truncated_normal(shape: Any, mean: float = ..., stddev: float = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def categorical(logits: Any, num_samples: int = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def randint(shape: Any, minval: int = ..., maxval: int = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def shuffle(x: Any, axis: int = ..., seed: Any = ...) -> Any: ...
def gamma(shape: Any, alpha: Any = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def binomial(shape: Any, counts: Any = ..., probabilities: Any = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def beta(shape: Any, alpha: Any = ..., beta: Any = ..., dtype: Any = ..., seed: Any = ...) -> Any: ...
def dropout(inputs: Any, rate: float = ..., noise_shape: Any = ..., seed: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
