from typing import Any


class CustomObjectScope: ...
class KerasFileEditor: ...
class custom_object_scope: ...

def deserialize_keras_object(*args: Any, **kwargs: Any) -> Any: ...
def get_custom_objects(*args: Any, **kwargs: Any) -> Any: ...
def get_registered_name(*args: Any, **kwargs: Any) -> Any: ...
def get_registered_object(*args: Any, **kwargs: Any) -> Any: ...
def load_model(*args: Any, **kwargs: Any) -> Any: ...
def load_weights(*args: Any, **kwargs: Any) -> Any: ...
def register_keras_serializable(*args: Any, **kwargs: Any) -> Any: ...
def save_model(*args: Any, **kwargs: Any) -> Any: ...
def save_weights(*args: Any, **kwargs: Any) -> Any: ...
def serialize_keras_object(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
