from typing import Any


class Config: ...
class CustomObjectScope: ...
class FeatureSpace: ...
class Progbar: ...
class PyDataset: ...
class Sequence: ...
class custom_object_scope: ...

def array_to_img(*args: Any, **kwargs: Any) -> Any: ...
def audio_dataset_from_directory(*args: Any, **kwargs: Any) -> Any: ...
def clear_session(*args: Any, **kwargs: Any) -> Any: ...
def deserialize_keras_object(*args: Any, **kwargs: Any) -> Any: ...
def disable_interactive_logging(*args: Any, **kwargs: Any) -> Any: ...
def enable_interactive_logging(*args: Any, **kwargs: Any) -> Any: ...
def get_custom_objects(*args: Any, **kwargs: Any) -> Any: ...
def get_file(*args: Any, **kwargs: Any) -> Any: ...
def get_registered_name(*args: Any, **kwargs: Any) -> Any: ...
def get_registered_object(*args: Any, **kwargs: Any) -> Any: ...
def get_source_inputs(*args: Any, **kwargs: Any) -> Any: ...
def image_dataset_from_directory(*args: Any, **kwargs: Any) -> Any: ...
def img_to_array(*args: Any, **kwargs: Any) -> Any: ...
def is_interactive_logging_enabled(*args: Any, **kwargs: Any) -> Any: ...
def is_keras_tensor(*args: Any, **kwargs: Any) -> Any: ...
def load_img(*args: Any, **kwargs: Any) -> Any: ...
def model_to_dot(*args: Any, **kwargs: Any) -> Any: ...
def normalize(*args: Any, **kwargs: Any) -> Any: ...
def pack_x_y_sample_weight(*args: Any, **kwargs: Any) -> Any: ...
def pad_sequences(*args: Any, **kwargs: Any) -> Any: ...
def plot_model(*args: Any, **kwargs: Any) -> Any: ...
def register_keras_serializable(*args: Any, **kwargs: Any) -> Any: ...
def save_img(*args: Any, **kwargs: Any) -> Any: ...
def serialize_keras_object(*args: Any, **kwargs: Any) -> Any: ...
def set_random_seed(*args: Any, **kwargs: Any) -> Any: ...
def split_dataset(*args: Any, **kwargs: Any) -> Any: ...
def standardize_dtype(*args: Any, **kwargs: Any) -> Any: ...
def text_dataset_from_directory(*args: Any, **kwargs: Any) -> Any: ...
def timeseries_dataset_from_array(*args: Any, **kwargs: Any) -> Any: ...
def to_categorical(*args: Any, **kwargs: Any) -> Any: ...
def unpack_x_y_sample_weight(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
