"""Type stubs for tensorflow.random module - provided by LegacyKerasPatch."""

from collections.abc import Sequence
from typing import Any

import tensorflow as tf

from . import experimental as experimental

class Algorithm:
    AUTO_SELECT: Any
    PHILOX: Any
    THREEFRY: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Generator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def make_seeds(self, count: int = ...) -> tf.Tensor: ...
    def normal(self, shape: tf.Tensor | Sequence[int], mean: float = ..., stddev: float = ..., dtype: Any = ..., name: str | None = ...) -> tf.Tensor: ...
    def split(self, count: int = ...) -> list[Generator]: ...
    def truncated_normal(self, shape: Any, mean: float = ..., stddev: float = ..., dtype: Any = ..., name: str | None = ...) -> tf.Tensor: ...
    def uniform(self, shape: Any, minval: float = ..., maxval: float | None = ..., dtype: Any = ..., name: str | None = ...) -> tf.Tensor: ...
    @staticmethod
    def from_seed(seed: int, alg: Any = ...) -> Generator: ...
    @staticmethod
    def from_non_deterministic_state(alg: Any = ...) -> Generator: ...
    @staticmethod
    def from_key_counter(key: Any, counter: Any, alg: Any = ...) -> Generator: ...

def all_candidate_sampler(true_classes: tf.Tensor, num_true: int, num_sampled: int, unique: bool, seed: int | None = ..., name: str | None = ...) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor]: ...
def categorical(logits: tf.Tensor, num_samples: int | tf.Tensor, dtype: Any = ..., seed: int | None = ..., name: str | None = ...) -> tf.Tensor: ...
def create_rng_state(seed: int, alg: Any) -> Any: ...
def fixed_unigram_candidate_sampler(true_classes: tf.Tensor, num_true: int, num_sampled: int, unique: bool, range_max: int, vocab_file: str = ..., distortion: float = ..., num_reserved_ids: int = ..., num_shards: int = ..., shard: int = ..., unigrams: Sequence[float] = ..., seed: int | None = ..., name: str | None = ...) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor]: ...
def fold_in(seed: tf.Tensor | Sequence[int], data: int, alg: Any = ...) -> int: ...
def gamma(shape: tf.Tensor | Sequence[int], alpha: tf.Tensor | float | Sequence[float], beta: tf.Tensor | float | Sequence[float] | None = ..., dtype: Any = ..., seed: int | None = ..., name: str | None = ...) -> tf.Tensor: ...
def get_global_generator() -> Generator: ...
def learned_unigram_candidate_sampler(true_classes: tf.Tensor, num_true: int, num_sampled: int, unique: bool, range_max: int, seed: int | None = ..., name: str | None = ...) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor]: ...
def log_uniform_candidate_sampler(true_classes: tf.Tensor, num_true: int, num_sampled: int, unique: bool, range_max: int, seed: int | None = ..., name: str | None = ...) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor]: ...
def normal(shape: tf.Tensor | Sequence[int], mean: float = ..., stddev: float = ..., dtype: Any = ..., seed: int | None = ..., name: str | None = ...) -> tf.Tensor: ...
def poisson(shape: Any, lam: Any, dtype: Any = ..., seed: int | None = ..., name: str | None = ...) -> tf.Tensor: ...
def set_global_generator(generator: Generator) -> None: ...
def set_seed(seed: int) -> None: ...
def shuffle(value: tf.Tensor, seed: int | None = ..., name: str | None = ...) -> tf.Tensor: ...
def split(seed: tf.Tensor | Sequence[int], num: int = ..., alg: Any = ...) -> tf.Tensor: ...
def stateless_binomial(shape: Any, seed: tuple[int, int] | tf.Tensor, counts: tf.Tensor, probs: tf.Tensor, output_dtype: Any = ..., name: str | None = ...) -> tf.Tensor: ...
def stateless_categorical(logits: tf.Tensor, num_samples: int | tf.Tensor, seed: tuple[int, int] | tf.Tensor, dtype: Any = ..., name: str | None = ...) -> tf.Tensor: ...
def stateless_gamma(shape: Any, seed: tuple[int, int] | tf.Tensor, alpha: tf.Tensor, beta: tf.Tensor | None = ..., dtype: Any = ..., name: str | None = ...) -> tf.Tensor: ...
def stateless_normal(shape: tf.Tensor | Sequence[int], seed: tuple[int, int] | tf.Tensor, mean: float | tf.Tensor = ..., stddev: float | tf.Tensor = ..., dtype: Any = ..., name: str | None = ..., alg: Any = ...) -> tf.Tensor: ...
def stateless_parameterized_truncated_normal(shape: tf.Tensor | Sequence[int], seed: tuple[int, int] | tf.Tensor, means: float | tf.Tensor = ..., stddevs: float | tf.Tensor = ..., minvals: tf.Tensor | float = ..., maxvals: tf.Tensor | float = ..., name: str | None = ...) -> tf.Tensor: ...
def stateless_poisson(shape: tf.Tensor | Sequence[int], seed: tuple[int, int] | tf.Tensor, lam: tf.Tensor, dtype: Any = ..., name: str | None = ...) -> tf.Tensor: ...
def stateless_truncated_normal(shape: tf.Tensor | Sequence[int], seed: tuple[int, int] | tf.Tensor, mean: float | tf.Tensor = ..., stddev: float | tf.Tensor = ..., dtype: Any = ..., name: str | None = ..., alg: Any = ...) -> tf.Tensor: ...
def stateless_uniform(shape: tf.Tensor | Sequence[int], seed: tuple[int, int] | tf.Tensor, minval: float | tf.Tensor = ..., maxval: float | tf.Tensor | None = ..., dtype: Any = ..., name: str | None = ..., alg: Any = ...) -> tf.Tensor: ...
def truncated_normal(shape: tf.Tensor | Sequence[int], mean: float | tf.Tensor = ..., stddev: float | tf.Tensor = ..., dtype: Any = ..., seed: int | None = ..., name: str | None = ...) -> tf.Tensor: ...
def uniform(shape: tf.Tensor | Sequence[int], minval: float | tf.Tensor = ..., maxval: float | tf.Tensor | None = ..., dtype: Any = ..., seed: int | None = ..., name: str | None = ...) -> tf.Tensor: ...
def uniform_candidate_sampler(true_classes: tf.Tensor, num_true: int, num_sampled: int, unique: bool, range_max: int, seed: int | None = ..., name: str | None = ...) -> tuple[tf.Tensor, tf.Tensor, tf.Tensor]: ...

def __getattr__(name: str) -> Any: ...
