"""Type stubs for tensorflow.random module - provided by LegacyKerasPatch."""

from typing import Any

from . import experimental as experimental

class Algorithm:
    AUTO_SELECT: Any
    PHILOX: Any
    THREEFRY: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Generator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def make_seeds(self, count: Any = ...) -> Any: ...
    def normal(self, shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
    def split(self, count: Any = ...) -> Any: ...
    def truncated_normal(self, shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
    def uniform(self, shape: Any, minval: Any = ..., maxval: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
    @staticmethod
    def from_seed(seed: Any) -> "Generator": ...
    @staticmethod
    def from_non_deterministic_state() -> "Generator": ...

def all_candidate_sampler(true_classes: Any, num_true: Any, num_sampled: Any, unique: Any, seed: Any = ..., name: Any = ...) -> Any: ...
def categorical(logits: Any, num_samples: Any, dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def create_rng_state(seed: Any, alg: Any) -> Any: ...
def fixed_unigram_candidate_sampler(true_classes: Any, num_true: Any, num_sampled: Any, unique: Any, range_max: Any, vocab_file: Any = ..., distortion: Any = ..., num_reserved_ids: Any = ..., num_shards: Any = ..., shard: Any = ..., unigrams: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def fold_in(seed: Any, data: Any, alg: Any = ...) -> Any: ...
def gamma(shape: Any, alpha: Any, beta: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def get_global_generator() -> Generator: ...
def learned_unigram_candidate_sampler(true_classes: Any, num_true: Any, num_sampled: Any, unique: Any, range_max: Any, seed: Any = ..., name: Any = ...) -> Any: ...
def log_uniform_candidate_sampler(true_classes: Any, num_true: Any, num_sampled: Any, unique: Any, range_max: Any, seed: Any = ..., name: Any = ...) -> Any: ...
def normal(shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def poisson(shape: Any, lam: Any, dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def set_global_generator(generator: Any) -> None: ...
def set_seed(seed: Any) -> None: ...
def shuffle(value: Any, seed: Any = ..., name: Any = ...) -> Any: ...
def split(seed: Any, num: Any = ..., alg: Any = ...) -> Any: ...
def stateless_binomial(shape: Any, seed: Any, counts: Any, probs: Any, output_dtype: Any = ..., name: Any = ...) -> Any: ...
def stateless_categorical(logits: Any, num_samples: Any, seed: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def stateless_gamma(shape: Any, seed: Any, alpha: Any, beta: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def stateless_normal(shape: Any, seed: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ..., alg: Any = ...) -> Any: ...
def stateless_parameterized_truncated_normal(shape: Any, seed: Any, means: Any = ..., stddevs: Any = ..., minvals: Any = ..., maxvals: Any = ..., name: Any = ...) -> Any: ...
def stateless_poisson(shape: Any, seed: Any, lam: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def stateless_truncated_normal(shape: Any, seed: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ..., alg: Any = ...) -> Any: ...
def stateless_uniform(shape: Any, seed: Any, minval: Any = ..., maxval: Any = ..., dtype: Any = ..., name: Any = ..., alg: Any = ...) -> Any: ...
def truncated_normal(shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def uniform(shape: Any, minval: Any = ..., maxval: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def uniform_candidate_sampler(true_classes: Any, num_true: Any, num_sampled: Any, unique: Any, range_max: Any, seed: Any = ..., name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
