"""Type stubs for tensorflow.random module - provided by LegacyKerasPatch."""

from typing import Any

class Generator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def make_seeds(self, count: Any = ...) -> Any: ...
    def normal(self, shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
    def split(self, count: Any = ...) -> Any: ...
    def truncated_normal(self, shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
    def uniform(self, shape: Any, minval: Any = ..., maxval: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
    @staticmethod
    def from_seed(seed: Any) -> "Generator": ...
    @staticmethod
    def from_non_deterministic_state() -> "Generator": ...

def categorical(logits: Any, num_samples: Any, dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
experimental: Any
def gamma(shape: Any, alpha: Any, beta: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def normal(shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def poisson(shape: Any, lam: Any, dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def set_seed(seed: Any) -> None: ...
def shuffle(value: Any, seed: Any = ..., name: Any = ...) -> Any: ...
def stateless_categorical(logits: Any, num_samples: Any, seed: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def stateless_normal(shape: Any, seed: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ..., alg: Any = ...) -> Any: ...
def stateless_truncated_normal(shape: Any, seed: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., name: Any = ..., alg: Any = ...) -> Any: ...
def stateless_uniform(shape: Any, seed: Any, minval: Any = ..., maxval: Any = ..., dtype: Any = ..., name: Any = ..., alg: Any = ...) -> Any: ...
def truncated_normal(shape: Any, mean: Any = ..., stddev: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...
def uniform(shape: Any, minval: Any = ..., maxval: Any = ..., dtype: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
