"""Setup configuration for LegacyKerasPatch."""

from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="legacy-keras-patch",
    version="1.0.0",
    author="Edward Huang",
    author_email="",
    description="Keras 3 ops compatibility layer for Keras 2 + TensorFlow",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/edwardyehuang/LegacyKerasPatch",
    packages=find_packages() + [
        "keras-stubs",
        "keras-stubs.ops",
        "keras-stubs.activations",
        "keras-stubs.applications",
        "keras-stubs.backend",
        "keras-stubs.callbacks",
        "keras-stubs.config",
        "keras-stubs.constraints",
        "keras-stubs.datasets",
        "keras-stubs.distribution",
        "keras-stubs.initializers",
        "keras-stubs.layers",
        "keras-stubs.losses",
        "keras-stubs.metrics",
        "keras-stubs.mixed_precision",
        "keras-stubs.models",
        "keras-stubs.optimizers",
        "keras-stubs.preprocessing",
        "keras-stubs.random",
        "keras-stubs.regularizers",
        "keras-stubs.saving",
        "keras-stubs.utils",
        "tensorflow-stubs",
        "tensorflow-stubs.python",
        "tensorflow-stubs.python.ops",
        "tensorflow-stubs.nn",
        "tensorflow-stubs.math",
        "tensorflow-stubs.linalg",
        "tensorflow-stubs.signal",
        "tensorflow-stubs.image",
        "tensorflow-stubs.bitwise",
        "tensorflow-stubs.random",
        "tensorflow-stubs.random.experimental",
        "tensorflow-stubs.raw_ops",
        "tensorflow-stubs.experimental",
        "tensorflow-stubs.experimental.dtensor",
        "tensorflow-stubs.experimental.numpy",
        "tensorflow-stubs.debugging",
        "tensorflow-stubs.autograph",
        "tensorflow-stubs.autograph.experimental",
        "tensorflow-stubs.config.experimental",
        "tensorflow-stubs.config.optimizer",
        "tensorflow-stubs.config.threading",
        "tensorflow-stubs.distribute",
        "tensorflow-stubs.distribute.cluster_resolver",
        "tensorflow-stubs.distribute.coordinator",
        "tensorflow-stubs.distribute.experimental",
        "tensorflow-stubs.data",
        "tensorflow-stubs.data.experimental",
        "tensorflow-stubs.io",
        "tensorflow-stubs.io.gfile",
        "tensorflow-stubs.tpu",
        "tensorflow-stubs.tpu.experimental",
    ],
    package_data={
        "legacy_keras_patch": ["py.typed", "ops/*.pyi", "random/*.pyi", "distribution/*.pyi"],
        "keras-stubs": [
            "__init__.pyi",
            "METADATA.toml",
            "ops/*.pyi",
            "activations/*.pyi",
            "applications/*.pyi",
            "backend/*.pyi",
            "callbacks/*.pyi",
            "config/*.pyi",
            "constraints/*.pyi",
            "datasets/*.pyi",
            "distribution/*.pyi",
            "initializers/*.pyi",
            "layers/*.pyi",
            "losses/*.pyi",
            "metrics/*.pyi",
            "mixed_precision/*.pyi",
            "models/*.pyi",
            "optimizers/*.pyi",
            "preprocessing/*.pyi",
            "random/*.pyi",
            "regularizers/*.pyi",
            "saving/*.pyi",
            "utils/*.pyi",
        ],
        "tensorflow-stubs": [
            "__init__.pyi",
            "METADATA.toml",
            "python/*.pyi",
            "python/*.py",
            "python/ops/*.pyi",
            "python/ops/*.py",
            "nn/*.pyi",
            "nn/*.py",
            "math/*.pyi",
            "math/*.py",
            "linalg/*.pyi",
            "signal/*.pyi",
            "image/*.pyi",
            "bitwise/*.pyi",
            "random/*.pyi",
            "random/experimental/*.pyi",
            "raw_ops/*.pyi",
            "experimental/*.pyi",
            "experimental/dtensor/*.pyi",
            "experimental/numpy/*.pyi",
            "debugging/*.pyi",
            "autograph/*.pyi",
            "autograph/experimental/*.pyi",
            "data/*.pyi",
            "data/experimental/*.pyi",
            "io/*.pyi",
            "io/gfile/*.pyi",
            "distribute/*.pyi",
            "distribute/cluster_resolver/*.pyi",
            "distribute/coordinator/*.pyi",
            "distribute/experimental/*.pyi",
            "tpu/*.pyi",
            "tpu/experimental/*.pyi",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.8",
    install_requires=[
        "tensorflow>=2.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0.0",
            "pytest-cov>=2.0.0",
        ],
    },
)
