"""Type stubs for tensorflow.autograph module - provided by LegacyKerasPatch."""

from typing import Any

from . import experimental as experimental

def to_graph(entity: Any, **kwargs: Any) -> Any: ...
def to_code(entity: Any, **kwargs: Any) -> Any: ...
def set_verbosity(level: Any, alsologtostdout: Any = ...) -> None: ...
def trace(log_level: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
