from typing import Any


class AUC: ...
class Accuracy: ...
class BinaryAccuracy: ...
class BinaryCrossentropy: ...
class BinaryIoU: ...
class CategoricalAccuracy: ...
class CategoricalCrossentropy: ...
class CategoricalHinge: ...
class ConcordanceCorrelation: ...
class CosineSimilarity: ...
class F1Score: ...
class FBetaScore: ...
class FalseNegatives: ...
class FalsePositives: ...
class Hinge: ...
class IoU: ...
class KLDivergence: ...
class LogCoshError: ...
class Mean: ...
class MeanAbsoluteError: ...
class MeanAbsolutePercentageError: ...
class MeanIoU: ...
class MeanMetricWrapper: ...
class MeanSquaredError: ...
class MeanSquaredLogarithmicError: ...
class Metric: ...
class OneHotIoU: ...
class OneHotMeanIoU: ...
class PearsonCorrelation: ...
class Poisson: ...
class Precision: ...
class PrecisionAtRecall: ...
class R2Score: ...
class Recall: ...
class RecallAtPrecision: ...
class RootMeanSquaredError: ...
class SensitivityAtSpecificity: ...
class SparseCategoricalAccuracy: ...
class SparseCategoricalCrossentropy: ...
class SparseTopKCategoricalAccuracy: ...
class SpecificityAtSensitivity: ...
class SquaredHinge: ...
class Sum: ...
class TopKCategoricalAccuracy: ...
class TrueNegatives: ...
class TruePositives: ...

def binary_accuracy(*args: Any, **kwargs: Any) -> Any: ...
def binary_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def binary_focal_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_accuracy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_focal_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_hinge(*args: Any, **kwargs: Any) -> Any: ...
def concordance_correlation(*args: Any, **kwargs: Any) -> Any: ...
def deserialize(*args: Any, **kwargs: Any) -> Any: ...
def get(*args: Any, **kwargs: Any) -> Any: ...
def hinge(*args: Any, **kwargs: Any) -> Any: ...
def huber(*args: Any, **kwargs: Any) -> Any: ...
def kl_divergence(*args: Any, **kwargs: Any) -> Any: ...
def log_cosh(*args: Any, **kwargs: Any) -> Any: ...
def mean_absolute_error(*args: Any, **kwargs: Any) -> Any: ...
def mean_absolute_percentage_error(*args: Any, **kwargs: Any) -> Any: ...
def mean_squared_error(*args: Any, **kwargs: Any) -> Any: ...
def mean_squared_logarithmic_error(*args: Any, **kwargs: Any) -> Any: ...
def pearson_correlation(*args: Any, **kwargs: Any) -> Any: ...
def poisson(*args: Any, **kwargs: Any) -> Any: ...
def serialize(*args: Any, **kwargs: Any) -> Any: ...
def sparse_categorical_accuracy(*args: Any, **kwargs: Any) -> Any: ...
def sparse_categorical_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def sparse_top_k_categorical_accuracy(*args: Any, **kwargs: Any) -> Any: ...
def squared_hinge(*args: Any, **kwargs: Any) -> Any: ...
def top_k_categorical_accuracy(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
