"""Type stubs for tensorflow.signal module - provided by LegacyKerasPatch."""

from typing import Any

def bartlett_window(window_length: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def blackman_window(window_length: Any, periodic: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def dct(input: Any, type: Any = ..., n: Any = ..., axis: Any = ..., norm: Any = ..., name: Any = ...) -> Any: ...
def fft(input: Any, name: Any = ...) -> Any: ...
def fft2d(input: Any, name: Any = ...) -> Any: ...
def fft3d(input: Any, name: Any = ...) -> Any: ...
def fftshift(x: Any, axes: Any = ..., name: Any = ...) -> Any: ...
def frame(signal: Any, frame_length: Any, frame_step: Any, pad_end: Any = ..., pad_value: Any = ..., axis: Any = ..., name: Any = ...) -> Any: ...
def hamming_window(window_length: Any, periodic: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def hann_window(window_length: Any, periodic: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def idct(input: Any, type: Any = ..., n: Any = ..., axis: Any = ..., norm: Any = ..., name: Any = ...) -> Any: ...
def ifft(input: Any, name: Any = ...) -> Any: ...
def ifft2d(input: Any, name: Any = ...) -> Any: ...
def ifft3d(input: Any, name: Any = ...) -> Any: ...
def ifftshift(x: Any, axes: Any = ..., name: Any = ...) -> Any: ...
def inverse_mdct(mdcts: Any, window_fn: Any = ..., norm: Any = ..., name: Any = ...) -> Any: ...
def inverse_stft(stfts: Any, frame_length: Any, frame_step: Any, fft_length: Any = ..., window_fn: Any = ..., name: Any = ...) -> Any: ...
def inverse_stft_window_fn(frame_step: Any, forward_window_fn: Any = ..., name: Any = ...) -> Any: ...
def irfft(input_tensor: Any, fft_length: Any = ..., name: Any = ...) -> Any: ...
def kaiser_bessel_derived_window(window_length: Any, beta: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def kaiser_window(window_length: Any, beta: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def linear_to_mel_weight_matrix(num_mel_bins: Any = ..., num_spectrogram_bins: Any = ..., sample_rate: Any = ..., lower_edge_hertz: Any = ..., upper_edge_hertz: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def mdct(signals: Any, frame_length: Any, window_fn: Any = ..., pad_end: Any = ..., norm: Any = ..., name: Any = ...) -> Any: ...
def mfccs_from_log_mel_spectrograms(log_mel_spectrograms: Any, name: Any = ...) -> Any: ...
def overlap_and_add(signal: Any, frame_step: Any, name: Any = ...) -> Any: ...
def rfft(input_tensor: Any, fft_length: Any = ..., name: Any = ...) -> Any: ...
def stft(signals: Any, frame_length: Any, frame_step: Any, fft_length: Any = ..., window_fn: Any = ..., pad_end: Any = ..., name: Any = ...) -> Any: ...
def vorbis_window(window_length: Any, dtype: Any = ..., name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
