"""Type stubs for tensorflow.image module - provided by LegacyKerasPatch."""

from typing import Any

class ResizeMethod:
    AREA: Any
    BICUBIC: Any
    BILINEAR: Any
    GAUSSIAN: Any
    LANCZOS3: Any
    LANCZOS5: Any
    MITCHELLCUBIC: Any
    NEAREST_NEIGHBOR: Any

def adjust_brightness(image: Any, delta: Any) -> Any: ...
def adjust_contrast(images: Any, contrast_factor: Any) -> Any: ...
def adjust_gamma(image: Any, gamma: Any = ..., gain: Any = ...) -> Any: ...
def adjust_hue(image: Any, delta: Any, name: Any = ...) -> Any: ...
def adjust_jpeg_quality(image: Any, jpeg_quality: Any, name: Any = ...) -> Any: ...
def adjust_saturation(image: Any, saturation_factor: Any, name: Any = ...) -> Any: ...
def central_crop(image: Any, central_fraction: Any) -> Any: ...
def convert_image_dtype(image: Any, dtype: Any, saturate: Any = ..., name: Any = ...) -> Any: ...
def crop_and_resize(image: Any, boxes: Any, box_indices: Any, crop_size: Any, method: Any = ..., extrapolation_value: Any = ..., name: Any = ...) -> Any: ...
def crop_to_bounding_box(image: Any, offset_height: Any, offset_width: Any, target_height: Any, target_width: Any) -> Any: ...
def decode_bmp(contents: Any, channels: Any = ..., name: Any = ...) -> Any: ...
def decode_gif(contents: Any, name: Any = ...) -> Any: ...
def decode_image(contents: Any, channels: Any = ..., dtype: Any = ..., name: Any = ..., expand_animations: Any = ...) -> Any: ...
def decode_jpeg(contents: Any, channels: Any = ..., ratio: Any = ..., fancy_upscaling: Any = ..., try_recover_truncated: Any = ..., acceptable_fraction: Any = ..., dct_method: Any = ..., name: Any = ...) -> Any: ...
def decode_png(contents: Any, channels: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def draw_bounding_boxes(images: Any, boxes: Any, colors: Any = ..., name: Any = ...) -> Any: ...
def encode_jpeg(image: Any, format: Any = ..., quality: Any = ..., progressive: Any = ..., optimize_size: Any = ..., chroma_downsampling: Any = ..., density_unit: Any = ..., x_density: Any = ..., y_density: Any = ..., xmp_metadata: Any = ..., name: Any = ...) -> Any: ...
def encode_png(image: Any, compression: Any = ..., name: Any = ...) -> Any: ...
def extract_patches(images: Any, sizes: Any, strides: Any, rates: Any, padding: Any, name: Any = ...) -> Any: ...
def flip_left_right(image: Any) -> Any: ...
def flip_up_down(image: Any) -> Any: ...
def grayscale_to_rgb(images: Any, name: Any = ...) -> Any: ...
def hsv_to_rgb(images: Any, name: Any = ...) -> Any: ...
def non_max_suppression(boxes: Any, scores: Any, max_output_size: Any, iou_threshold: Any = ..., score_threshold: Any = ..., name: Any = ...) -> Any: ...
def pad_to_bounding_box(image: Any, offset_height: Any, offset_width: Any, target_height: Any, target_width: Any) -> Any: ...
def per_image_standardization(image: Any) -> Any: ...
def psnr(a: Any, b: Any, max_val: Any, name: Any = ...) -> Any: ...
def random_brightness(image: Any, max_delta: Any, seed: Any = ...) -> Any: ...
def random_contrast(image: Any, lower: Any, upper: Any, seed: Any = ...) -> Any: ...
def random_crop(value: Any, size: Any, seed: Any = ..., name: Any = ...) -> Any: ...
def random_flip_left_right(image: Any, seed: Any = ...) -> Any: ...
def random_flip_up_down(image: Any, seed: Any = ...) -> Any: ...
def random_hue(image: Any, max_delta: Any, seed: Any = ...) -> Any: ...
def random_jpeg_quality(image: Any, min_jpeg_quality: Any, max_jpeg_quality: Any, seed: Any = ...) -> Any: ...
def random_saturation(image: Any, lower: Any, upper: Any, seed: Any = ...) -> Any: ...
def resize(images: Any, size: Any, method: Any = ..., preserve_aspect_ratio: Any = ..., antialias: Any = ..., name: Any = ...) -> Any: ...
def resize_with_crop_or_pad(image: Any, target_height: Any, target_width: Any) -> Any: ...
def resize_with_pad(image: Any, target_height: Any, target_width: Any, method: Any = ..., antialias: Any = ...) -> Any: ...
def rgb_to_grayscale(images: Any, name: Any = ...) -> Any: ...
def rgb_to_hsv(images: Any, name: Any = ...) -> Any: ...
def rgb_to_yiq(images: Any) -> Any: ...
def rgb_to_yuv(images: Any) -> Any: ...
def rot90(image: Any, k: Any = ..., name: Any = ...) -> Any: ...
def sample_distorted_bounding_box(image_size: Any, bounding_boxes: Any, seed: Any = ..., min_object_covered: Any = ..., aspect_ratio_range: Any = ..., area_range: Any = ..., max_attempts: Any = ..., use_image_if_no_bounding_boxes: Any = ..., name: Any = ...) -> Any: ...
def sobel_edges(image: Any) -> Any: ...
def ssim(img1: Any, img2: Any, max_val: Any, filter_size: Any = ..., filter_sigma: Any = ..., k1: Any = ..., k2: Any = ...) -> Any: ...
def ssim_multiscale(img1: Any, img2: Any, max_val: Any, power_factors: Any = ..., filter_size: Any = ..., filter_sigma: Any = ..., k1: Any = ..., k2: Any = ...) -> Any: ...
def stateless_random_brightness(image: Any, max_delta: Any, seed: Any) -> Any: ...
def stateless_random_contrast(image: Any, lower: Any, upper: Any, seed: Any) -> Any: ...
def stateless_random_crop(value: Any, size: Any, seed: Any, name: Any = ...) -> Any: ...
def stateless_random_flip_left_right(image: Any, seed: Any) -> Any: ...
def stateless_random_flip_up_down(image: Any, seed: Any) -> Any: ...
def stateless_random_hue(image: Any, max_delta: Any, seed: Any) -> Any: ...
def stateless_random_jpeg_quality(image: Any, min_jpeg_quality: Any, max_jpeg_quality: Any, seed: Any) -> Any: ...
def stateless_random_saturation(image: Any, lower: Any, upper: Any, seed: Any) -> Any: ...
def stateless_sample_distorted_bounding_box(image_size: Any, bounding_boxes: Any, seed: Any, min_object_covered: Any = ..., aspect_ratio_range: Any = ..., area_range: Any = ..., max_attempts: Any = ..., use_image_if_no_bounding_boxes: Any = ..., name: Any = ...) -> Any: ...
def total_variation(images: Any, name: Any = ...) -> Any: ...
def transpose(image: Any, name: Any = ...) -> Any: ...
def yiq_to_rgb(images: Any) -> Any: ...
def yuv_to_rgb(images: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
