from typing import Any


def ConvNeXtBase(*args: Any, **kwargs: Any) -> Any: ...
def ConvNeXtLarge(*args: Any, **kwargs: Any) -> Any: ...
def ConvNeXtSmall(*args: Any, **kwargs: Any) -> Any: ...
def ConvNeXtTiny(*args: Any, **kwargs: Any) -> Any: ...
def ConvNeXtXLarge(*args: Any, **kwargs: Any) -> Any: ...
def DenseNet121(*args: Any, **kwargs: Any) -> Any: ...
def DenseNet169(*args: Any, **kwargs: Any) -> Any: ...
def DenseNet201(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB0(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB1(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB2(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB3(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB4(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB5(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB6(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetB7(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetV2B0(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetV2B1(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetV2B2(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetV2B3(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetV2L(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetV2M(*args: Any, **kwargs: Any) -> Any: ...
def EfficientNetV2S(*args: Any, **kwargs: Any) -> Any: ...
def InceptionResNetV2(*args: Any, **kwargs: Any) -> Any: ...
def InceptionV3(*args: Any, **kwargs: Any) -> Any: ...
def MobileNet(*args: Any, **kwargs: Any) -> Any: ...
def MobileNetV2(*args: Any, **kwargs: Any) -> Any: ...
def MobileNetV3Large(*args: Any, **kwargs: Any) -> Any: ...
def MobileNetV3Small(*args: Any, **kwargs: Any) -> Any: ...
def NASNetLarge(*args: Any, **kwargs: Any) -> Any: ...
def NASNetMobile(*args: Any, **kwargs: Any) -> Any: ...
def ResNet101(*args: Any, **kwargs: Any) -> Any: ...
def ResNet101V2(*args: Any, **kwargs: Any) -> Any: ...
def ResNet152(*args: Any, **kwargs: Any) -> Any: ...
def ResNet152V2(*args: Any, **kwargs: Any) -> Any: ...
def ResNet50(*args: Any, **kwargs: Any) -> Any: ...
def ResNet50V2(*args: Any, **kwargs: Any) -> Any: ...
def VGG16(*args: Any, **kwargs: Any) -> Any: ...
def VGG19(*args: Any, **kwargs: Any) -> Any: ...
def Xception(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
