from typing import Any


class DTypePolicy: ...
class LossScaleOptimizer: ...
class Policy: ...

def dtype_policy(*args: Any, **kwargs: Any) -> Any: ...
def global_policy(*args: Any, **kwargs: Any) -> Any: ...
def set_dtype_policy(*args: Any, **kwargs: Any) -> Any: ...
def set_global_policy(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
