"""Type stubs for tensorflow module - provided by LegacyKerasPatch."""

from typing import Any

from . import nn as nn
from . import math as math
from . import linalg as linalg
from . import signal as signal
from . import image as image
from . import bitwise as bitwise
from . import random as random
from . import raw_ops as raw_ops
from . import experimental as experimental
from . import debugging as debugging

# Common dtypes
float16: DType
float32: DType
float64: DType
bfloat16: DType
int8: DType
int16: DType
int32: DType
int64: DType
uint8: DType
uint16: DType
uint32: DType
uint64: DType
bool: DType
string: DType
complex64: DType
complex128: DType
newaxis: Any

# Core classes
class Tensor: ...
class Variable: ...
class TensorShape: ...
class DType: ...
class GradientTape:
    def __init__(self, persistent: bool = ..., watch_accessed_variables: bool = ...) -> None: ...
    def __enter__(self) -> "GradientTape": ...
    def __exit__(self, *args: Any) -> None: ...
    def watch(self, tensor: Any) -> None: ...
    def gradient(self, target: Any, sources: Any, **kwargs: Any) -> Any: ...
    def jacobian(self, target: Any, sources: Any, **kwargs: Any) -> Any: ...
class RaggedTensor: ...
class SparseTensor: ...
class TensorSpec: ...

# Core functions
def abs(x: Any, name: Any = ...) -> Any: ...
def acos(x: Any, name: Any = ...) -> Any: ...
def acosh(x: Any, name: Any = ...) -> Any: ...
def add(x: Any, y: Any, name: Any = ...) -> Any: ...
def argmax(input: Any, axis: Any = ..., output_type: Any = ..., name: Any = ...) -> Any: ...
def argmin(input: Any, axis: Any = ..., output_type: Any = ..., name: Any = ...) -> Any: ...
def argsort(values: Any, axis: Any = ..., direction: Any = ..., stable: Any = ..., name: Any = ...) -> Any: ...
def asin(x: Any, name: Any = ...) -> Any: ...
def asinh(x: Any, name: Any = ...) -> Any: ...
def atan(x: Any, name: Any = ...) -> Any: ...
def atanh(x: Any, name: Any = ...) -> Any: ...
def broadcast_to(input: Any, shape: Any, name: Any = ...) -> Any: ...
def cast(x: Any, dtype: Any, name: Any = ...) -> Any: ...
def clip_by_value(t: Any, clip_value_min: Any, clip_value_max: Any, name: Any = ...) -> Any: ...
def complex(real: Any, imag: Any, name: Any = ...) -> Any: ...
def concat(values: Any, axis: Any, name: Any = ...) -> Any: ...
def cond(pred: Any, true_fn: Any = ..., false_fn: Any = ..., name: Any = ...) -> Any: ...
def constant(value: Any, dtype: Any = ..., shape: Any = ..., name: Any = ...) -> Any: ...
def convert_to_tensor(value: Any, dtype: Any = ..., dtype_hint: Any = ..., name: Any = ...) -> Any: ...
def cos(x: Any, name: Any = ...) -> Any: ...
def cosh(x: Any, name: Any = ...) -> Any: ...
def custom_gradient(f: Any) -> Any: ...
def divide(x: Any, y: Any, name: Any = ...) -> Any: ...
def einsum(equation: Any, *inputs: Any, **kwargs: Any) -> Any: ...
def ensure_shape(x: Any, shape: Any, name: Any = ...) -> Any: ...
def equal(x: Any, y: Any, name: Any = ...) -> Any: ...
def exp(x: Any, name: Any = ...) -> Any: ...
def expand_dims(input: Any, axis: Any, name: Any = ...) -> Any: ...
def extract_volume_patches(input: Any, ksizes: Any, strides: Any, padding: Any, name: Any = ...) -> Any: ...
def eye(num_rows: Any, num_columns: Any = ..., batch_shape: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def fill(dims: Any, value: Any, name: Any = ...) -> Any: ...
def floor(x: Any, name: Any = ...) -> Any: ...
def function(func: Any = ..., input_signature: Any = ..., **kwargs: Any) -> Any: ...
def gather(params: Any, indices: Any, axis: Any = ..., batch_dims: Any = ..., name: Any = ...) -> Any: ...
def gather_nd(params: Any, indices: Any, batch_dims: Any = ..., name: Any = ...) -> Any: ...
def greater(x: Any, y: Any, name: Any = ...) -> Any: ...
def greater_equal(x: Any, y: Any, name: Any = ...) -> Any: ...
def histogram_fixed_width(values: Any, value_range: Any, nbins: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def identity(input: Any, name: Any = ...) -> Any: ...
def is_tensor(x: Any) -> Any: ...
def less(x: Any, y: Any, name: Any = ...) -> Any: ...
def less_equal(x: Any, y: Any, name: Any = ...) -> Any: ...
def linspace(start: Any, stop: Any, num: Any, name: Any = ..., axis: Any = ...) -> Any: ...
def map_fn(fn: Any, elems: Any, **kwargs: Any) -> Any: ...
def matmul(a: Any, b: Any, transpose_a: Any = ..., transpose_b: Any = ..., **kwargs: Any) -> Any: ...
def meshgrid(*args: Any, **kwargs: Any) -> Any: ...
def multiply(x: Any, y: Any, name: Any = ...) -> Any: ...
def ones(shape: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def ones_like(input: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def pad(tensor: Any, paddings: Any, mode: Any = ..., constant_values: Any = ..., name: Any = ...) -> Any: ...
def range(start: Any, limit: Any = ..., delta: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def reduce_all(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_any(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_logsumexp(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_max(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_mean(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_min(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_sum(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reshape(tensor: Any, shape: Any, name: Any = ...) -> Any: ...
def reverse(tensor: Any, axis: Any, name: Any = ...) -> Any: ...
def saturate_cast(value: Any, dtype: Any, name: Any = ...) -> Any: ...
def scalar_mul(scalar: Any, x: Any, name: Any = ...) -> Any: ...
def scan(fn: Any, elems: Any, initializer: Any = ..., **kwargs: Any) -> Any: ...
def scatter_nd(indices: Any, updates: Any, shape: Any, name: Any = ...) -> Any: ...
def searchsorted(sorted_sequence: Any, values: Any, side: Any = ..., out_type: Any = ..., name: Any = ...) -> Any: ...
def shape(input: Any, out_type: Any = ..., name: Any = ...) -> Any: ...
def sigmoid(x: Any, name: Any = ...) -> Any: ...
def sin(x: Any, name: Any = ...) -> Any: ...
def sinh(x: Any, name: Any = ...) -> Any: ...
def slice(input_: Any, begin: Any, size: Any, name: Any = ...) -> Any: ...
def sort(values: Any, axis: Any = ..., direction: Any = ..., name: Any = ...) -> Any: ...
def split(value: Any, num_or_size_splits: Any, axis: Any = ..., num: Any = ..., name: Any = ...) -> Any: ...
def sqrt(x: Any, name: Any = ...) -> Any: ...
def square(x: Any, name: Any = ...) -> Any: ...
def squeeze(input: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def stack(values: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def stop_gradient(input: Any, name: Any = ...) -> Any: ...
def subtract(x: Any, y: Any, name: Any = ...) -> Any: ...
def switch_case(branch_index: Any, branch_fns: Any, default: Any = ..., name: Any = ...) -> Any: ...
def tanh(x: Any, name: Any = ...) -> Any: ...
def tensor_scatter_nd_update(tensor: Any, indices: Any, updates: Any, name: Any = ...) -> Any: ...
def tensordot(a: Any, b: Any, axes: Any, name: Any = ...) -> Any: ...
def tile(input: Any, multiples: Any, name: Any = ...) -> Any: ...
def transpose(a: Any, perm: Any = ..., conjugate: Any = ..., name: Any = ...) -> Any: ...
def unstack(value: Any, num: Any = ..., axis: Any = ..., name: Any = ...) -> Any: ...
def vectorized_map(fn: Any, elems: Any, **kwargs: Any) -> Any: ...
def where(condition: Any, x: Any = ..., y: Any = ..., name: Any = ...) -> Any: ...
def while_loop(cond: Any, body: Any, loop_vars: Any, **kwargs: Any) -> Any: ...
def zeros(shape: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def zeros_like(input: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def one_hot(indices: Any, depth: Any, on_value: Any = ..., off_value: Any = ..., axis: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def maximum(x: Any, y: Any, name: Any = ...) -> Any: ...
def minimum(x: Any, y: Any, name: Any = ...) -> Any: ...
def negative(x: Any, name: Any = ...) -> Any: ...
def not_equal(x: Any, y: Any, name: Any = ...) -> Any: ...
def pow(x: Any, y: Any, name: Any = ...) -> Any: ...
def repeat(input: Any, repeats: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def round(x: Any, name: Any = ...) -> Any: ...
def sign(x: Any, name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
