"""Type stubs for tensorflow.nn module - provided by LegacyKerasPatch."""

from typing import Any

# Pooling operations
def avg_pool(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def avg_pool1d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def avg_pool2d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def avg_pool3d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool1d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool2d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...
def max_pool3d(input: Any, ksize: Any, strides: Any, padding: Any, data_format: Any = ..., name: Any = ...) -> Any: ...

# Convolution operations
def conv1d(input: Any, filters: Any, stride: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv1d_transpose(input: Any, filters: Any, output_shape: Any, strides: Any, padding: Any = ..., data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv2d(input: Any, filters: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv2d_transpose(input: Any, filters: Any, output_shape: Any, strides: Any, padding: Any = ..., data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv3d(input: Any, filters: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def conv3d_transpose(input: Any, filters: Any, output_shape: Any, strides: Any, padding: Any = ..., data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def depthwise_conv2d(input: Any, filter: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...
def separable_conv2d(input: Any, depthwise_filter: Any, pointwise_filter: Any, strides: Any, padding: Any, data_format: Any = ..., dilations: Any = ..., name: Any = ...) -> Any: ...

# Normalization and moments
def batch_normalization(x: Any, mean: Any, variance: Any, offset: Any, scale: Any, variance_epsilon: Any, name: Any = ...) -> Any: ...
def l2_normalize(x: Any, axis: Any = ..., epsilon: Any = ..., name: Any = ..., dim: Any = ...) -> Any: ...
def moments(x: Any, axes: Any, shift: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...

# Bias
def bias_add(value: Any, bias: Any, data_format: Any = ..., name: Any = ...) -> Any: ...

# Activations
def relu(features: Any, name: Any = ...) -> Any: ...
def relu6(features: Any, name: Any = ...) -> Any: ...
def leaky_relu(features: Any, alpha: Any = ..., name: Any = ...) -> Any: ...
def elu(features: Any, name: Any = ...) -> Any: ...
def selu(features: Any, name: Any = ...) -> Any: ...
def gelu(features: Any, approximate: Any = ..., name: Any = ...) -> Any: ...
def softmax(logits: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def log_softmax(logits: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def softplus(features: Any, name: Any = ...) -> Any: ...
def softsign(features: Any, name: Any = ...) -> Any: ...
def swish(x: Any) -> Any: ...
def sigmoid(x: Any, name: Any = ...) -> Any: ...
def tanh(x: Any, name: Any = ...) -> Any: ...
def silu(features: Any, beta: Any = ...) -> Any: ...
def log_sigmoid(x: Any, name: Any = ...) -> Any: ...

# Loss functions
def sigmoid_cross_entropy_with_logits(labels: Any = ..., logits: Any = ..., name: Any = ...) -> Any: ...
def softmax_cross_entropy_with_logits(labels: Any, logits: Any, axis: Any = ..., name: Any = ...) -> Any: ...
def sparse_softmax_cross_entropy_with_logits(labels: Any, logits: Any, name: Any = ...) -> Any: ...

# CTC operations
def ctc_beam_search_decoder(inputs: Any, sequence_length: Any, beam_width: Any = ..., top_paths: Any = ...) -> Any: ...
def ctc_greedy_decoder(inputs: Any, sequence_length: Any, merge_repeated: Any = ..., blank_index: Any = ...) -> Any: ...
def ctc_loss(labels: Any, logits: Any, label_length: Any, logit_length: Any, logits_time_major: Any = ..., unique: Any = ..., blank_index: Any = ..., name: Any = ...) -> Any: ...

# Dropout
def dropout(x: Any, rate: Any = ..., noise_shape: Any = ..., seed: Any = ..., name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
