from typing import Any


class BackupAndRestore: ...
class CSVLogger: ...
class Callback: ...
class CallbackList: ...
class EarlyStopping: ...
class History: ...
class LambdaCallback: ...
class LearningRateScheduler: ...
class ModelCheckpoint: ...
class ProgbarLogger: ...
class ReduceLROnPlateau: ...
class RemoteMonitor: ...
class SwapEMAWeights: ...
class TensorBoard: ...
class TerminateOnNaN: ...

def __getattr__(name: str) -> Any: ...
