"""Type stubs for tensorflow.random.experimental module - provided by LegacyKerasPatch."""

from typing import Any

import tensorflow as tf

from .. import Algorithm as Algorithm
from .. import Generator as Generator

def create_rng_state(seed: int, alg: Any) -> Any: ...
def get_global_generator() -> Generator: ...
def index_shuffle(index: tf.Tensor, seed: tf.Tensor, max_index: int) -> tf.Tensor: ...
def set_global_generator(generator: Generator) -> None: ...
def stateless_fold_in(seed: tf.Tensor | tuple[int, int], data: int, alg: Any = ...) -> tf.Tensor: ...
def stateless_shuffle(value: tf.Tensor, seed: tuple[int, int] | tf.Tensor, alg: Any = ..., name: str | None = ...) -> tf.Tensor: ...
def stateless_split(seed: tuple[int, int] | tf.Tensor, num: int = ..., alg: Any = ...) -> tf.Tensor: ...

def __getattr__(name: str) -> Any: ...
