"""Type stubs for tensorflow.random.experimental module - provided by LegacyKerasPatch."""

from typing import Any

from .. import Algorithm as Algorithm
from .. import Generator as Generator

def create_rng_state(seed: Any, alg: Any) -> Any: ...
def get_global_generator() -> Generator: ...
def index_shuffle(index: Any, seed: Any, max_index: Any) -> Any: ...
def set_global_generator(generator: Any) -> None: ...
def stateless_fold_in(seed: Any, data: Any, alg: Any = ...) -> Any: ...
def stateless_shuffle(value: Any, seed: Any, alg: Any = ..., name: Any = ...) -> Any: ...
def stateless_split(seed: Any, num: Any = ..., alg: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
