from typing import Any


class L1: ...
class L1L2: ...
class L2: ...
class OrthogonalRegularizer: ...
class Regularizer: ...
class l1: ...
class l1_l2: ...
class l2: ...
class orthogonal_regularizer: ...

def deserialize(*args: Any, **kwargs: Any) -> Any: ...
def get(*args: Any, **kwargs: Any) -> Any: ...
def serialize(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
