"""Type stubs for legacy_keras_patch.ops.image."""

from typing import Any, Optional, Union

def affine_transform(images: Any, transform: Any, interpolation: str = ..., fill_mode: str = ..., fill_value: float = ..., data_format: str = ...) -> Any: ...
def crop_images(images: Any, top_cropping: int, left_cropping: int, bottom_cropping: int, right_cropping: int, target_height: Optional[int] = ..., target_width: Optional[int] = ..., data_format: str = ...) -> Any: ...
def elastic_transform(images: Any, alpha: Any, sigma: Any, interpolation: str = ..., fill_mode: str = ..., fill_value: float = ..., seed: Any = ..., data_format: str = ...) -> Any: ...
def extract_patches(images: Any, size: Any, strides: Any = ..., dilation_rate: Any = ..., padding: str = ..., data_format: str = ...) -> Any: ...
def extract_patches_3d(images: Any, size: Any, strides: Any = ..., dilation_rate: Any = ..., padding: str = ..., data_format: str = ...) -> Any: ...
def gaussian_blur(images: Any, kernel_size: Any, sigma: Any, data_format: str = ...) -> Any: ...
def hsv_to_rgb(images: Any, data_format: str = ...) -> Any: ...
def map_coordinates(inputs: Any, coordinates: Any, order: int = ..., fill_mode: str = ..., fill_value: float = ...) -> Any: ...
def pad_images(images: Any, top_padding: int = ..., left_padding: int = ..., bottom_padding: int = ..., right_padding: int = ..., target_height: Optional[int] = ..., target_width: Optional[int] = ..., data_format: str = ...) -> Any: ...
def perspective_transform(images: Any, transform: Any, interpolation: str = ..., fill_mode: str = ..., fill_value: float = ..., data_format: str = ...) -> Any: ...
def resize(images: Any, size: Any, interpolation: str = ..., antialias: bool = ..., crop_to_aspect_ratio: bool = ..., pad_to_aspect_ratio: bool = ..., fill_mode: str = ..., fill_value: float = ..., data_format: str = ...) -> Any: ...
def rgb_to_grayscale(images: Any, data_format: str = ...) -> Any: ...
def rgb_to_hsv(images: Any, data_format: str = ...) -> Any: ...
def scale_and_translate(images: Any, scale: Any, translation: Any, interpolation: str = ..., fill_mode: str = ..., fill_value: float = ..., data_format: str = ...) -> Any: ...
