"""Type stubs for legacy_keras_patch.ops.linalg."""

from typing import Any, Optional, Tuple, Union

def cholesky(x: Any) -> Any: ...
def cholesky_inverse(x: Any) -> Any: ...
def det(x: Any) -> Any: ...
def eig(x: Any) -> Any: ...
def eigh(x: Any) -> Any: ...
def inv(x: Any) -> Any: ...
def jvp(primals: Any, tangents: Any, fn: Any) -> Any: ...
def lstsq(a: Any, b: Any, rcond: Optional[float] = ...) -> Any: ...
def lu_factor(x: Any) -> Any: ...
def norm(x: Any, ord: Any = ..., axis: Any = ..., keepdims: bool = ...) -> Any: ...
def qr(x: Any, mode: str = ...) -> Any: ...
def solve(a: Any, b: Any) -> Any: ...
def solve_triangular(a: Any, b: Any, lower: bool = ...) -> Any: ...
def svd(x: Any, full_matrices: bool = ..., compute_uv: bool = ...) -> Any: ...
