"""Type stubs for legacy_keras_patch.ops.nn."""

from typing import Any, Optional, Tuple, Union

def adaptive_average_pool(inputs: Any, output_size: Any, data_format: str = ...) -> Any: ...
def adaptive_max_pool(inputs: Any, output_size: Any, data_format: str = ...) -> Any: ...
def average_pool(inputs: Any, pool_size: Any, strides: Any = ..., padding: str = ..., data_format: str = ...) -> Any: ...
def batch_normalization(x: Any, mean: Any, variance: Any, axis: int, offset: Any = ..., scale: Any = ..., epsilon: float = ...) -> Any: ...
def binary_crossentropy(target: Any, output: Any, from_logits: bool = ...) -> Any: ...
def categorical_crossentropy(target: Any, output: Any, from_logits: bool = ..., axis: int = ...) -> Any: ...
def celu(x: Any, alpha: float = ...) -> Any: ...
def conv(inputs: Any, kernel: Any, strides: Any = ..., padding: str = ..., data_format: str = ..., dilation_rate: Any = ...) -> Any: ...
def conv_transpose(inputs: Any, kernel: Any, strides: Any, padding: str = ..., output_padding: Any = ..., data_format: str = ..., dilation_rate: Any = ...) -> Any: ...
def ctc_decode(inputs: Any, sequence_lengths: Any, strategy: str = ..., beam_width: int = ..., top_paths: int = ..., merge_repeated: bool = ..., mask_index: Any = ...) -> Any: ...
def ctc_loss(target: Any, output: Any, target_length: Any, output_length: Any, mask_index: int = ...) -> Any: ...
def depthwise_conv(inputs: Any, kernel: Any, strides: Any = ..., padding: str = ..., data_format: str = ..., dilation_rate: Any = ...) -> Any: ...
def dot_product_attention(query: Any, key: Any, value: Any, bias: Any = ..., mask: Any = ..., scale: Any = ..., is_causal: bool = ..., flash_attention: Any = ...) -> Any: ...
def elu(x: Any, alpha: float = ...) -> Any: ...
def gelu(x: Any, approximate: bool = ...) -> Any: ...
def glu(x: Any, axis: int = ...) -> Any: ...
def hard_shrink(x: Any, threshold: float = ...) -> Any: ...
def hard_sigmoid(x: Any) -> Any: ...
def hard_silu(x: Any) -> Any: ...
def hard_swish(x: Any) -> Any: ...
def hard_tanh(x: Any) -> Any: ...
def layer_normalization(x: Any, scale: Any = ..., offset: Any = ..., axis: int = ..., epsilon: float = ...) -> Any: ...
def leaky_relu(x: Any, negative_slope: float = ...) -> Any: ...
def log_sigmoid(x: Any) -> Any: ...
def log_softmax(x: Any, axis: int = ...) -> Any: ...
def max_pool(inputs: Any, pool_size: Any, strides: Any = ..., padding: str = ..., data_format: str = ...) -> Any: ...
def moments(x: Any, axes: Any, keepdims: bool = ..., synchronized: bool = ...) -> Any: ...
def multi_hot(inputs: Any, num_classes: int, axis: int = ..., dtype: Any = ..., sparse: bool = ...) -> Any: ...
def normalize(x: Any, axis: int = ..., order: int = ..., epsilon: float = ...) -> Any: ...
def one_hot(x: Any, num_classes: int, axis: int = ..., dtype: Any = ..., sparse: bool = ...) -> Any: ...
def polar(x: Any) -> Any: ...
def psnr(x1: Any, x2: Any, max_val: float) -> Any: ...
def relu(x: Any) -> Any: ...
def relu6(x: Any) -> Any: ...
def rms_normalization(x: Any, scale: Any = ..., offset: Any = ..., axis: int = ..., epsilon: float = ...) -> Any: ...
def selu(x: Any) -> Any: ...
def separable_conv(inputs: Any, depthwise_kernel: Any, pointwise_kernel: Any, strides: Any = ..., padding: str = ..., data_format: str = ..., dilation_rate: Any = ...) -> Any: ...
def sigmoid(x: Any) -> Any: ...
def silu(x: Any) -> Any: ...
def soft_shrink(x: Any, threshold: float = ...) -> Any: ...
def softmax(x: Any, axis: int = ...) -> Any: ...
def softplus(x: Any) -> Any: ...
def softsign(x: Any) -> Any: ...
def sparse_categorical_crossentropy(target: Any, output: Any, from_logits: bool = ..., axis: int = ...) -> Any: ...
def sparse_plus(x: Any) -> Any: ...
def sparse_sigmoid(x: Any) -> Any: ...
def sparsemax(x: Any, axis: int = ...) -> Any: ...
def squareplus(x: Any, b: int = ...) -> Any: ...
def swish(x: Any) -> Any: ...
def tanh_shrink(x: Any) -> Any: ...
def threshold(x: Any, threshold_value: Any, value: Any) -> Any: ...
def unfold(inputs: Any, kernel_size: Any, strides: Any = ..., dilation_rate: Any = ..., padding: str = ..., data_format: str = ...) -> Any: ...
