"""Type stubs for legacy_keras_patch.ops.numpy_ops."""

from typing import Any, Optional, Sequence, Tuple, Union

def abs(x: Any) -> Any: ...
def absolute(x: Any) -> Any: ...
def add(x1: Any, x2: Any) -> Any: ...
def all(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def amax(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def amin(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def angle(x: Any) -> Any: ...
def any(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def append(x1: Any, x2: Any, axis: Optional[int] = ...) -> Any: ...
def arange(start: Any, stop: Any = ..., step: Any = ..., dtype: Any = ...) -> Any: ...
def arccos(x: Any) -> Any: ...
def arccosh(x: Any) -> Any: ...
def arcsin(x: Any) -> Any: ...
def arcsinh(x: Any) -> Any: ...
def arctan(x: Any) -> Any: ...
def arctan2(y: Any, x: Any) -> Any: ...
def arctanh(x: Any) -> Any: ...
def argmax(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def argmin(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def argpartition(x: Any, kth: int, axis: int = ...) -> Any: ...
def argsort(x: Any, axis: int = ...) -> Any: ...
def array(x: Any, dtype: Any = ...) -> Any: ...
def array_split(x: Any, indices_or_sections: Any, axis: int = ...) -> Any: ...
def average(x: Any, axis: Optional[int] = ..., weights: Any = ..., keepdims: bool = ...) -> Any: ...
def bartlett(M: int) -> Any: ...
def bincount(x: Any, weights: Any = ..., minlength: int = ...) -> Any: ...
def bitwise_and(x1: Any, x2: Any) -> Any: ...
def bitwise_invert(x: Any) -> Any: ...
def bitwise_left_shift(x: Any, n: Any) -> Any: ...
def bitwise_not(x: Any) -> Any: ...
def bitwise_or(x1: Any, x2: Any) -> Any: ...
def bitwise_right_shift(x: Any, n: Any) -> Any: ...
def bitwise_xor(x1: Any, x2: Any) -> Any: ...
def blackman(M: int) -> Any: ...
def broadcast_to(x: Any, shape: Any) -> Any: ...
def cbrt(x: Any) -> Any: ...
def ceil(x: Any) -> Any: ...
def clip(x: Any, x_min: Any, x_max: Any) -> Any: ...
def concatenate(arrays: Any, axis: int = ...) -> Any: ...
def conj(x: Any) -> Any: ...
def conjugate(x: Any) -> Any: ...
def copy(x: Any) -> Any: ...
def corrcoef(x: Any, rowvar: bool = ...) -> Any: ...
def correlate(a: Any, v: Any, mode: str = ...) -> Any: ...
def cos(x: Any) -> Any: ...
def cosh(x: Any) -> Any: ...
def count_nonzero(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def cross(x1: Any, x2: Any, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: Optional[int] = ...) -> Any: ...
def cumprod(x: Any, axis: Optional[int] = ..., dtype: Any = ...) -> Any: ...
def cumsum(x: Any, axis: Optional[int] = ..., dtype: Any = ...) -> Any: ...
def deg2rad(x: Any) -> Any: ...
def diag(v: Any, k: int = ...) -> Any: ...
def diagflat(v: Any, k: int = ...) -> Any: ...
def diagonal(a: Any, offset: int = ..., axis1: int = ..., axis2: int = ...) -> Any: ...
def diff(a: Any, n: int = ..., axis: int = ...) -> Any: ...
def digitize(x: Any, bins: Any, right: bool = ...) -> Any: ...
def divide(x1: Any, x2: Any) -> Any: ...
def divide_no_nan(x1: Any, x2: Any) -> Any: ...
def dot(a: Any, b: Any) -> Any: ...
def einsum(subscripts: str, *operands: Any) -> Any: ...
def empty(shape: Any, dtype: Any = ...) -> Any: ...
def empty_like(x: Any, dtype: Any = ...) -> Any: ...
def equal(x1: Any, x2: Any) -> Any: ...
def exp(x: Any) -> Any: ...
def exp2(x: Any) -> Any: ...
def expand_dims(x: Any, axis: int) -> Any: ...
def expm1(x: Any) -> Any: ...
def eye(N: int, M: Optional[int] = ..., k: int = ..., dtype: Any = ...) -> Any: ...
def flip(x: Any, axis: Optional[int] = ...) -> Any: ...
def floor(x: Any) -> Any: ...
def floor_divide(x1: Any, x2: Any) -> Any: ...
def full(shape: Any, fill_value: Any, dtype: Any = ...) -> Any: ...
def full_like(x: Any, fill_value: Any, dtype: Any = ...) -> Any: ...
def gcd(x1: Any, x2: Any) -> Any: ...
def get_item(x: Any, key: Any) -> Any: ...
def greater(x1: Any, x2: Any) -> Any: ...
def greater_equal(x1: Any, x2: Any) -> Any: ...
def hamming(M: int) -> Any: ...
def hanning(M: int) -> Any: ...
def heaviside(x1: Any, x2: Any) -> Any: ...
def histogram(x: Any, bins: Any = ..., range: Any = ...) -> Any: ...
def hstack(arrays: Any) -> Any: ...
def hypot(x1: Any, x2: Any) -> Any: ...
def identity(n: int, dtype: Any = ...) -> Any: ...
def imag(x: Any) -> Any: ...
def inner(a: Any, b: Any) -> Any: ...
def isclose(a: Any, b: Any, rtol: float = ..., atol: float = ..., equal_nan: bool = ...) -> Any: ...
def isfinite(x: Any) -> Any: ...
def isin(element: Any, test_elements: Any, assume_unique: bool = ..., invert: bool = ...) -> Any: ...
def isinf(x: Any) -> Any: ...
def isnan(x: Any) -> Any: ...
def isneginf(x: Any) -> Any: ...
def isposinf(x: Any) -> Any: ...
def isreal(x: Any) -> Any: ...
def kaiser(M: int, beta: float) -> Any: ...
def kron(a: Any, b: Any) -> Any: ...
def lcm(x1: Any, x2: Any) -> Any: ...
def ldexp(x1: Any, x2: Any) -> Any: ...
def left_shift(x: Any, n: Any) -> Any: ...
def less(x1: Any, x2: Any) -> Any: ...
def less_equal(x1: Any, x2: Any) -> Any: ...
def linspace(start: Any, stop: Any, num: int = ..., endpoint: bool = ..., dtype: Any = ...) -> Any: ...
def log(x: Any) -> Any: ...
def log10(x: Any) -> Any: ...
def log1p(x: Any) -> Any: ...
def log2(x: Any) -> Any: ...
def logaddexp(x1: Any, x2: Any) -> Any: ...
def logaddexp2(x1: Any, x2: Any) -> Any: ...
def logical_and(x1: Any, x2: Any) -> Any: ...
def logical_not(x: Any) -> Any: ...
def logical_or(x1: Any, x2: Any) -> Any: ...
def logical_xor(x1: Any, x2: Any) -> Any: ...
def logspace(start: Any, stop: Any, num: int = ..., endpoint: bool = ..., base: float = ..., dtype: Any = ...) -> Any: ...
def matmul(x1: Any, x2: Any) -> Any: ...
def max(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def maximum(x1: Any, x2: Any) -> Any: ...
def mean(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def median(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def meshgrid(*arrays: Any, indexing: str = ...) -> Any: ...
def min(x: Any, axis: Optional[int] = ..., keepdims: bool = ...) -> Any: ...
def minimum(x1: Any, x2: Any) -> Any: ...
def mod(x1: Any, x2: Any) -> Any: ...
def moveaxis(x: Any, source: Any, destination: Any) -> Any: ...
def multiply(x1: Any, x2: Any) -> Any: ...
def nan_to_num(x: Any, nan: float = ..., posinf: Optional[float] = ..., neginf: Optional[float] = ...) -> Any: ...
def ndim(x: Any) -> int: ...
def negative(x: Any) -> Any: ...
def nonzero(x: Any) -> Any: ...
def not_equal(x1: Any, x2: Any) -> Any: ...
def ones(shape: Any, dtype: Any = ...) -> Any: ...
def ones_like(x: Any, dtype: Any = ...) -> Any: ...
def outer(a: Any, b: Any) -> Any: ...
def pad(x: Any, pad_width: Any, mode: str = ..., constant_values: Any = ...) -> Any: ...
def power(x1: Any, x2: Any) -> Any: ...
def prod(x: Any, axis: Optional[int] = ..., keepdims: bool = ..., dtype: Any = ...) -> Any: ...
def quantile(x: Any, q: Any, axis: Optional[int] = ..., method: str = ..., keepdims: bool = ...) -> Any: ...
def ravel(x: Any) -> Any: ...
def real(x: Any) -> Any: ...
def reciprocal(x: Any) -> Any: ...
def repeat(x: Any, repeats: Any, axis: Optional[int] = ...) -> Any: ...
def reshape(x: Any, new_shape: Any) -> Any: ...
def right_shift(x: Any, n: Any) -> Any: ...
def roll(x: Any, shift: Any, axis: Optional[int] = ...) -> Any: ...
def rot90(x: Any, k: int = ..., axes: Any = ...) -> Any: ...
def round(x: Any, decimals: int = ...) -> Any: ...
def searchsorted(sorted_sequence: Any, values: Any, side: str = ...) -> Any: ...
def select(condlist: Any, choicelist: Any, default: Any = ...) -> Any: ...
def sign(x: Any) -> Any: ...
def signbit(x: Any) -> Any: ...
def sin(x: Any) -> Any: ...
def sinh(x: Any) -> Any: ...
def size(x: Any, axis: Optional[int] = ...) -> Any: ...
def slogdet(x: Any) -> Any: ...
def sort(x: Any, axis: int = ...) -> Any: ...
def split(x: Any, indices_or_sections: Any, axis: int = ...) -> Any: ...
def sqrt(x: Any) -> Any: ...
def square(x: Any) -> Any: ...
def squeeze(x: Any, axis: Optional[int] = ...) -> Any: ...
def stack(arrays: Any, axis: int = ...) -> Any: ...
def std(x: Any, axis: Optional[int] = ..., keepdims: bool = ..., ddof: int = ...) -> Any: ...
def subtract(x1: Any, x2: Any) -> Any: ...
def sum(x: Any, axis: Optional[int] = ..., keepdims: bool = ..., dtype: Any = ...) -> Any: ...
def swapaxes(x: Any, axis1: int, axis2: int) -> Any: ...
def take(x: Any, indices: Any, axis: Optional[int] = ...) -> Any: ...
def take_along_axis(arr: Any, indices: Any, axis: int) -> Any: ...
def tan(x: Any) -> Any: ...
def tanh(x: Any) -> Any: ...
def tensordot(a: Any, b: Any, axes: Any = ...) -> Any: ...
def tile(x: Any, reps: Any) -> Any: ...
def trace(x: Any, offset: int = ..., axis1: int = ..., axis2: int = ...) -> Any: ...
def transpose(x: Any, axes: Optional[Any] = ...) -> Any: ...
def trapezoid(y: Any, x: Any = ..., dx: float = ..., axis: int = ...) -> Any: ...
def tri(N: int, M: Optional[int] = ..., k: int = ..., dtype: Any = ...) -> Any: ...
def tril(x: Any, k: int = ...) -> Any: ...
def triu(x: Any, k: int = ...) -> Any: ...
def true_divide(x1: Any, x2: Any) -> Any: ...
def trunc(x: Any) -> Any: ...
def unravel_index(indices: Any, shape: Any) -> Any: ...
def vander(x: Any, N: Optional[int] = ..., increasing: bool = ...) -> Any: ...
def var(x: Any, axis: Optional[int] = ..., keepdims: bool = ..., ddof: int = ...) -> Any: ...
def vdot(a: Any, b: Any) -> Any: ...
def vectorize(pyfunc: Any, otypes: Any = ..., signature: Any = ...) -> Any: ...
def view(x: Any, dtype: Any) -> Any: ...
def vstack(arrays: Any) -> Any: ...
def where(condition: Any, x: Any = ..., y: Any = ...) -> Any: ...
def zeros(shape: Any, dtype: Any = ...) -> Any: ...
def zeros_like(x: Any, dtype: Any = ...) -> Any: ...
