"""Type stubs for tensorflow.math module - provided by LegacyKerasPatch."""

from typing import Any

def abs(x: Any, name: Any = ...) -> Any: ...
def acos(x: Any, name: Any = ...) -> Any: ...
def acosh(x: Any, name: Any = ...) -> Any: ...
def add(x: Any, y: Any, name: Any = ...) -> Any: ...
def angle(input: Any, name: Any = ...) -> Any: ...
def asin(x: Any, name: Any = ...) -> Any: ...
def asinh(x: Any, name: Any = ...) -> Any: ...
def atan(x: Any, name: Any = ...) -> Any: ...
def atan2(y: Any, x: Any, name: Any = ...) -> Any: ...
def atanh(x: Any, name: Any = ...) -> Any: ...
def bessel_i0(x: Any, name: Any = ...) -> Any: ...
def bessel_i0e(x: Any, name: Any = ...) -> Any: ...
def bessel_i1(x: Any, name: Any = ...) -> Any: ...
def bessel_i1e(x: Any, name: Any = ...) -> Any: ...
def bincount(arr: Any, weights: Any = ..., minlength: Any = ..., maxlength: Any = ..., dtype: Any = ..., name: Any = ..., axis: Any = ..., binary_output: Any = ...) -> Any: ...
def ceil(x: Any, name: Any = ...) -> Any: ...
def conj(x: Any, name: Any = ...) -> Any: ...
def cos(x: Any, name: Any = ...) -> Any: ...
def cosh(x: Any, name: Any = ...) -> Any: ...
def count_nonzero(input: Any, axis: Any = ..., keepdims: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def cumsum(x: Any, axis: Any = ..., exclusive: Any = ..., reverse: Any = ..., name: Any = ...) -> Any: ...
def cumprod(x: Any, axis: Any = ..., exclusive: Any = ..., reverse: Any = ..., name: Any = ...) -> Any: ...
def digamma(x: Any, name: Any = ...) -> Any: ...
def divide_no_nan(x: Any, y: Any, name: Any = ...) -> Any: ...
def erf(x: Any, name: Any = ...) -> Any: ...
def erfc(x: Any, name: Any = ...) -> Any: ...
def erfinv(x: Any, name: Any = ...) -> Any: ...
def exp(x: Any, name: Any = ...) -> Any: ...
def expm1(x: Any, name: Any = ...) -> Any: ...
def floor(x: Any, name: Any = ...) -> Any: ...
def floordiv(x: Any, y: Any, name: Any = ...) -> Any: ...
def gcd(x: Any, y: Any, name: Any = ...) -> Any: ...
def igamma(a: Any, x: Any, name: Any = ...) -> Any: ...
def igammac(a: Any, x: Any, name: Any = ...) -> Any: ...
def imag(input: Any, name: Any = ...) -> Any: ...
def in_top_k(targets: Any, predictions: Any, k: Any, name: Any = ...) -> Any: ...
def is_finite(x: Any, name: Any = ...) -> Any: ...
def is_inf(x: Any, name: Any = ...) -> Any: ...
def is_nan(x: Any, name: Any = ...) -> Any: ...
def l2_normalize(x: Any, axis: Any = ..., epsilon: Any = ..., name: Any = ...) -> Any: ...
def lbeta(x: Any, name: Any = ...) -> Any: ...
def lgamma(x: Any, name: Any = ...) -> Any: ...
def log(x: Any, name: Any = ...) -> Any: ...
def log1p(x: Any, name: Any = ...) -> Any: ...
def log_sigmoid(x: Any, name: Any = ...) -> Any: ...
def logical_and(x: Any, y: Any, name: Any = ...) -> Any: ...
def logical_not(x: Any, name: Any = ...) -> Any: ...
def logical_or(x: Any, y: Any, name: Any = ...) -> Any: ...
def logical_xor(x: Any, y: Any, name: Any = ...) -> Any: ...
def maximum(x: Any, y: Any, name: Any = ...) -> Any: ...
def minimum(x: Any, y: Any, name: Any = ...) -> Any: ...
def multiply(x: Any, y: Any, name: Any = ...) -> Any: ...
def negative(x: Any, name: Any = ...) -> Any: ...
def not_equal(x: Any, y: Any, name: Any = ...) -> Any: ...
def pow(x: Any, y: Any, name: Any = ...) -> Any: ...
def real(input: Any, name: Any = ...) -> Any: ...
def reciprocal(x: Any, name: Any = ...) -> Any: ...
def reduce_euclidean_norm(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_max(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_mean(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_min(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_std(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_sum(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def reduce_variance(input_tensor: Any, axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def rint(x: Any, name: Any = ...) -> Any: ...
def round(x: Any, name: Any = ...) -> Any: ...
def rsqrt(x: Any, name: Any = ...) -> Any: ...
def scalar_mul(scalar: Any, x: Any, name: Any = ...) -> Any: ...
def segment_max(data: Any, segment_ids: Any, name: Any = ...) -> Any: ...
def segment_mean(data: Any, segment_ids: Any, name: Any = ...) -> Any: ...
def segment_min(data: Any, segment_ids: Any, name: Any = ...) -> Any: ...
def segment_prod(data: Any, segment_ids: Any, name: Any = ...) -> Any: ...
def segment_sum(data: Any, segment_ids: Any, name: Any = ...) -> Any: ...
def sigmoid(x: Any, name: Any = ...) -> Any: ...
def sign(x: Any, name: Any = ...) -> Any: ...
def sin(x: Any, name: Any = ...) -> Any: ...
def sinh(x: Any, name: Any = ...) -> Any: ...
def softplus(features: Any, name: Any = ...) -> Any: ...
def sqrt(x: Any, name: Any = ...) -> Any: ...
def square(x: Any, name: Any = ...) -> Any: ...
def subtract(x: Any, y: Any, name: Any = ...) -> Any: ...
def tan(x: Any, name: Any = ...) -> Any: ...
def tanh(x: Any, name: Any = ...) -> Any: ...
def top_k(input: Any, k: Any = ..., sorted: Any = ..., name: Any = ...) -> Any: ...
def truediv(x: Any, y: Any, name: Any = ...) -> Any: ...
def unsorted_segment_max(data: Any, segment_ids: Any, num_segments: Any, name: Any = ...) -> Any: ...
def unsorted_segment_mean(data: Any, segment_ids: Any, num_segments: Any, name: Any = ...) -> Any: ...
def unsorted_segment_min(data: Any, segment_ids: Any, num_segments: Any, name: Any = ...) -> Any: ...
def unsorted_segment_prod(data: Any, segment_ids: Any, num_segments: Any, name: Any = ...) -> Any: ...
def unsorted_segment_sqrt_n(data: Any, segment_ids: Any, num_segments: Any, name: Any = ...) -> Any: ...
def unsorted_segment_sum(data: Any, segment_ids: Any, num_segments: Any, name: Any = ...) -> Any: ...
def xdivy(x: Any, y: Any, name: Any = ...) -> Any: ...
def xlogy(x: Any, y: Any, name: Any = ...) -> Any: ...
def zero_fraction(value: Any, name: Any = ...) -> Any: ...
def zeta(x: Any, q: Any, name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
