from typing import Any


def backend(*args: Any, **kwargs: Any) -> Any: ...
def disable_flash_attention(*args: Any, **kwargs: Any) -> Any: ...
def disable_interactive_logging(*args: Any, **kwargs: Any) -> Any: ...
def disable_traceback_filtering(*args: Any, **kwargs: Any) -> Any: ...
def dtype_policy(*args: Any, **kwargs: Any) -> Any: ...
def enable_flash_attention(*args: Any, **kwargs: Any) -> Any: ...
def enable_interactive_logging(*args: Any, **kwargs: Any) -> Any: ...
def enable_traceback_filtering(*args: Any, **kwargs: Any) -> Any: ...
def enable_unsafe_deserialization(*args: Any, **kwargs: Any) -> Any: ...
def epsilon(*args: Any, **kwargs: Any) -> Any: ...
def floatx(*args: Any, **kwargs: Any) -> Any: ...
def image_data_format(*args: Any, **kwargs: Any) -> Any: ...
def is_flash_attention_enabled(*args: Any, **kwargs: Any) -> Any: ...
def is_interactive_logging_enabled(*args: Any, **kwargs: Any) -> Any: ...
def is_nnx_enabled(*args: Any, **kwargs: Any) -> Any: ...
def is_traceback_filtering_enabled(*args: Any, **kwargs: Any) -> Any: ...
def max_epochs(*args: Any, **kwargs: Any) -> Any: ...
def max_steps_per_epoch(*args: Any, **kwargs: Any) -> Any: ...
def set_backend(*args: Any, **kwargs: Any) -> Any: ...
def set_dtype_policy(*args: Any, **kwargs: Any) -> Any: ...
def set_epsilon(*args: Any, **kwargs: Any) -> Any: ...
def set_floatx(*args: Any, **kwargs: Any) -> Any: ...
def set_image_data_format(*args: Any, **kwargs: Any) -> Any: ...
def set_max_epochs(*args: Any, **kwargs: Any) -> Any: ...
def set_max_steps_per_epoch(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
