from typing import Any


class BinaryCrossentropy: ...
class BinaryFocalCrossentropy: ...
class CTC: ...
class CategoricalCrossentropy: ...
class CategoricalFocalCrossentropy: ...
class CategoricalGeneralizedCrossEntropy: ...
class CategoricalHinge: ...
class Circle: ...
class CosineSimilarity: ...
class Dice: ...
class Hinge: ...
class Huber: ...
class KLDivergence: ...
class LogCosh: ...
class Loss: ...
class MeanAbsoluteError: ...
class MeanAbsolutePercentageError: ...
class MeanSquaredError: ...
class MeanSquaredLogarithmicError: ...
class Poisson: ...
class SparseCategoricalCrossentropy: ...
class SquaredHinge: ...
class Tversky: ...

def binary_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def binary_focal_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_focal_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_generalized_cross_entropy(*args: Any, **kwargs: Any) -> Any: ...
def categorical_hinge(*args: Any, **kwargs: Any) -> Any: ...
def circle(*args: Any, **kwargs: Any) -> Any: ...
def cosine_similarity(*args: Any, **kwargs: Any) -> Any: ...
def ctc(*args: Any, **kwargs: Any) -> Any: ...
def deserialize(*args: Any, **kwargs: Any) -> Any: ...
def dice(*args: Any, **kwargs: Any) -> Any: ...
def get(*args: Any, **kwargs: Any) -> Any: ...
def hinge(*args: Any, **kwargs: Any) -> Any: ...
def huber(*args: Any, **kwargs: Any) -> Any: ...
def kl_divergence(*args: Any, **kwargs: Any) -> Any: ...
def log_cosh(*args: Any, **kwargs: Any) -> Any: ...
def mean_absolute_error(*args: Any, **kwargs: Any) -> Any: ...
def mean_absolute_percentage_error(*args: Any, **kwargs: Any) -> Any: ...
def mean_squared_error(*args: Any, **kwargs: Any) -> Any: ...
def mean_squared_logarithmic_error(*args: Any, **kwargs: Any) -> Any: ...
def poisson(*args: Any, **kwargs: Any) -> Any: ...
def serialize(*args: Any, **kwargs: Any) -> Any: ...
def sparse_categorical_crossentropy(*args: Any, **kwargs: Any) -> Any: ...
def squared_hinge(*args: Any, **kwargs: Any) -> Any: ...
def tversky(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
