"""Type stubs for tensorflow.bitwise module - provided by LegacyKerasPatch."""

from typing import Any

def bitwise_and(x: Any, y: Any, name: Any = ...) -> Any: ...
def bitwise_or(x: Any, y: Any, name: Any = ...) -> Any: ...
def bitwise_xor(x: Any, y: Any, name: Any = ...) -> Any: ...
def invert(x: Any, name: Any = ...) -> Any: ...
def left_shift(x: Any, y: Any, name: Any = ...) -> Any: ...
def right_shift(x: Any, y: Any, name: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
