from typing import Any


class Constant: ...
class GlorotNormal: ...
class GlorotUniform: ...
class HeNormal: ...
class HeUniform: ...
class Identity: ...
class IdentityInitializer: ...
class Initializer: ...
class LecunNormal: ...
class LecunUniform: ...
class Ones: ...
class Orthogonal: ...
class OrthogonalInitializer: ...
class RandomNormal: ...
class RandomUniform: ...
class STFT: ...
class STFTInitializer: ...
class TruncatedNormal: ...
class VarianceScaling: ...
class Zeros: ...
class constant: ...
class glorot_normal: ...
class glorot_uniform: ...
class he_normal: ...
class he_uniform: ...
class identity: ...
class lecun_normal: ...
class lecun_uniform: ...
class ones: ...
class orthogonal: ...
class random_normal: ...
class random_uniform: ...
class stft: ...
class truncated_normal: ...
class variance_scaling: ...
class zeros: ...

def deserialize(*args: Any, **kwargs: Any) -> Any: ...
def get(*args: Any, **kwargs: Any) -> Any: ...
def serialize(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
