"""Type stubs for tensorflow.debugging module - provided by LegacyKerasPatch."""

from typing import Any

def assert_all_finite(x: Any, message: Any = ..., name: Any = ...) -> Any: ...
def assert_equal(x: Any, y: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_greater(x: Any, y: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_greater_equal(x: Any, y: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_integer(x: Any, message: Any = ..., name: Any = ...) -> Any: ...
def assert_less(x: Any, y: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_less_equal(x: Any, y: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_near(x: Any, y: Any, rtol: Any = ..., atol: Any = ..., message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_negative(x: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_non_negative(x: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_non_positive(x: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_none_equal(x: Any, y: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_positive(x: Any, message: Any = ..., summarize: Any = ..., name: Any = ...) -> Any: ...
def assert_proper_iterable(values: Any) -> None: ...
def assert_rank(x: Any, rank: Any, message: Any = ..., name: Any = ...) -> Any: ...
def assert_rank_at_least(x: Any, rank: Any, message: Any = ..., name: Any = ...) -> Any: ...
def assert_rank_in(x: Any, ranks: Any, message: Any = ..., name: Any = ...) -> Any: ...
def assert_same_float_dtype(tensors: Any = ..., dtype: Any = ...) -> Any: ...
def assert_scalar(tensor: Any, message: Any = ..., name: Any = ...) -> Any: ...
def assert_shapes(shapes: Any, data: Any = ..., summarize: Any = ..., message: Any = ..., name: Any = ...) -> Any: ...
def assert_type(tensor: Any, tf_type: Any, message: Any = ..., name: Any = ...) -> Any: ...
def check_numerics(tensor: Any, message: Any, name: Any = ...) -> Any: ...
def disable_check_numerics() -> None: ...
def enable_check_numerics(stack_height_limit: Any = ..., path_length_limit: Any = ...) -> None: ...
def disable_traceback_filtering() -> None: ...
def enable_traceback_filtering() -> None: ...
def is_traceback_filtering_enabled() -> bool: ...
def is_numeric_tensor(tensor: Any) -> Any: ...
def set_log_device_placement(enabled: Any) -> None: ...
def get_log_device_placement() -> bool: ...

experimental: Any

def __getattr__(name: str) -> Any: ...
