"""Type stubs for keras module with ops support from LegacyKerasPatch."""

from typing import Any

from . import ops as ops
from . import activations as activations
from . import applications as applications
from . import backend as backend
from . import callbacks as callbacks
from . import config as config
from . import constraints as constraints
from . import datasets as datasets
from . import distribution as distribution
from . import initializers as initializers
from . import layers as layers
from . import losses as losses
from . import metrics as metrics
from . import mixed_precision as mixed_precision
from . import models as models
from . import optimizers as optimizers
from . import preprocessing as preprocessing
from . import random as random
from . import regularizers as regularizers
from . import saving as saving
from . import utils as utils

class DTypePolicy: ...
class FloatDTypePolicy: ...
class Function: ...
class Initializer: ...
class InputSpec: ...
class KerasTensor: ...
class Layer: ...
class Loss: ...
class Metric: ...
class Model: ...
class Operation: ...
class Optimizer: ...
class Quantizer: ...
class Regularizer: ...
class Sequential: ...
class StatelessScope: ...
class SymbolicScope: ...
class Variable: ...
class name_scope: ...

def Input(*args: Any, **kwargs: Any) -> Any: ...
def device(*args: Any, **kwargs: Any) -> Any: ...
def version() -> str: ...

def __getattr__(name: str) -> Any: ...
