from typing import Any


def backend(*args: Any, **kwargs: Any) -> Any: ...
def clear_session(*args: Any, **kwargs: Any) -> Any: ...
def epsilon(*args: Any, **kwargs: Any) -> Any: ...
def floatx(*args: Any, **kwargs: Any) -> Any: ...
def get_uid(*args: Any, **kwargs: Any) -> Any: ...
def image_data_format(*args: Any, **kwargs: Any) -> Any: ...
def is_float_dtype(*args: Any, **kwargs: Any) -> Any: ...
def is_int_dtype(*args: Any, **kwargs: Any) -> Any: ...
def is_keras_tensor(*args: Any, **kwargs: Any) -> Any: ...
def result_type(*args: Any, **kwargs: Any) -> Any: ...
def set_epsilon(*args: Any, **kwargs: Any) -> Any: ...
def set_floatx(*args: Any, **kwargs: Any) -> Any: ...
def set_image_data_format(*args: Any, **kwargs: Any) -> Any: ...
def standardize_dtype(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
