"""Type stubs for tensorflow.io.gfile module - provided by LegacyKerasPatch."""

from typing import Any

from tensorflow.python.platform.gfile import GFile as GFile

def copy(src: Any, dst: Any, overwrite: Any = ...) -> Any: ...
def exists(path: Any) -> Any: ...
def get_registered_schemes() -> Any: ...
def glob(pattern: Any) -> Any: ...
def isdir(path: Any) -> Any: ...
def join(path: Any, *paths: Any) -> Any: ...
def listdir(path: Any) -> Any: ...
def makedirs(path: Any) -> Any: ...
def mkdir(path: Any) -> Any: ...
def remove(path: Any) -> Any: ...
def rename(src: Any, dst: Any, overwrite: Any = ...) -> Any: ...
def rmtree(path: Any) -> Any: ...
def stat(path: Any) -> Any: ...
def walk(top: Any, topdown: Any = ..., onerror: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
