from typing import Any


class Model: ...
class Sequential: ...

def clone_model(*args: Any, **kwargs: Any) -> Any: ...
def load_model(*args: Any, **kwargs: Any) -> Any: ...
def model_from_json(*args: Any, **kwargs: Any) -> Any: ...
def save_model(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
