from typing import Any


class Adadelta: ...
class Adafactor: ...
class Adagrad: ...
class Adam: ...
class AdamW: ...
class Adamax: ...
class Ftrl: ...
class Lamb: ...
class Lion: ...
class LossScaleOptimizer: ...
class Muon: ...
class Nadam: ...
class Optimizer: ...
class RMSprop: ...
class SGD: ...

def deserialize(*args: Any, **kwargs: Any) -> Any: ...
def get(*args: Any, **kwargs: Any) -> Any: ...
def serialize(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
