from typing import Any


def celu(*args: Any, **kwargs: Any) -> Any: ...
def deserialize(*args: Any, **kwargs: Any) -> Any: ...
def elu(*args: Any, **kwargs: Any) -> Any: ...
def exponential(*args: Any, **kwargs: Any) -> Any: ...
def gelu(*args: Any, **kwargs: Any) -> Any: ...
def get(*args: Any, **kwargs: Any) -> Any: ...
def glu(*args: Any, **kwargs: Any) -> Any: ...
def hard_shrink(*args: Any, **kwargs: Any) -> Any: ...
def hard_sigmoid(*args: Any, **kwargs: Any) -> Any: ...
def hard_silu(*args: Any, **kwargs: Any) -> Any: ...
def hard_swish(*args: Any, **kwargs: Any) -> Any: ...
def hard_tanh(*args: Any, **kwargs: Any) -> Any: ...
def leaky_relu(*args: Any, **kwargs: Any) -> Any: ...
def linear(*args: Any, **kwargs: Any) -> Any: ...
def log_sigmoid(*args: Any, **kwargs: Any) -> Any: ...
def log_softmax(*args: Any, **kwargs: Any) -> Any: ...
def mish(*args: Any, **kwargs: Any) -> Any: ...
def relu(*args: Any, **kwargs: Any) -> Any: ...
def relu6(*args: Any, **kwargs: Any) -> Any: ...
def selu(*args: Any, **kwargs: Any) -> Any: ...
def serialize(*args: Any, **kwargs: Any) -> Any: ...
def sigmoid(*args: Any, **kwargs: Any) -> Any: ...
def silu(*args: Any, **kwargs: Any) -> Any: ...
def soft_shrink(*args: Any, **kwargs: Any) -> Any: ...
def softmax(*args: Any, **kwargs: Any) -> Any: ...
def softplus(*args: Any, **kwargs: Any) -> Any: ...
def softsign(*args: Any, **kwargs: Any) -> Any: ...
def sparse_plus(*args: Any, **kwargs: Any) -> Any: ...
def sparse_sigmoid(*args: Any, **kwargs: Any) -> Any: ...
def sparsemax(*args: Any, **kwargs: Any) -> Any: ...
def squareplus(*args: Any, **kwargs: Any) -> Any: ...
def swish(*args: Any, **kwargs: Any) -> Any: ...
def tanh(*args: Any, **kwargs: Any) -> Any: ...
def tanh_shrink(*args: Any, **kwargs: Any) -> Any: ...
def threshold(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
