"""Type stubs for tensorflow.linalg module - provided by LegacyKerasPatch."""

from typing import Any

def adjoint(matrix: Any, name: Any = ...) -> Any: ...
def band_part(input: Any, num_lower: Any, num_upper: Any, name: Any = ...) -> Any: ...
def cholesky(input: Any, name: Any = ...) -> Any: ...
def cholesky_solve(chol: Any, rhs: Any, name: Any = ...) -> Any: ...
def cross(a: Any, b: Any, name: Any = ...) -> Any: ...
def det(input: Any, name: Any = ...) -> Any: ...
def diag(diagonal: Any, name: Any = ..., **kwargs: Any) -> Any: ...
def diag_part(input: Any, name: Any = ..., **kwargs: Any) -> Any: ...
def eig(tensor: Any, name: Any = ...) -> Any: ...
def eigh(tensor: Any, name: Any = ...) -> Any: ...
def eigvals(tensor: Any, name: Any = ...) -> Any: ...
def eigvalsh(tensor: Any, name: Any = ...) -> Any: ...
def expm(input: Any, name: Any = ...) -> Any: ...
def global_norm(t_list: Any, name: Any = ...) -> Any: ...
def inv(input: Any, adjoint: Any = ..., name: Any = ...) -> Any: ...
def logdet(matrix: Any, name: Any = ...) -> Any: ...
def lstsq(matrix: Any, rhs: Any, l2_regularizer: Any = ..., fast: Any = ..., name: Any = ...) -> Any: ...
def lu(input: Any, output_idx_type: Any = ..., name: Any = ...) -> Any: ...
def matmul(a: Any, b: Any, transpose_a: Any = ..., transpose_b: Any = ..., adjoint_a: Any = ..., adjoint_b: Any = ..., a_is_sparse: Any = ..., b_is_sparse: Any = ..., output_type: Any = ..., name: Any = ...) -> Any: ...
def matrix_rank(a: Any, tol: Any = ..., validate_args: Any = ..., name: Any = ...) -> Any: ...
def matrix_transpose(a: Any, name: Any = ..., conjugate: Any = ...) -> Any: ...
def norm(tensor: Any, ord: Any = ..., axis: Any = ..., keepdims: Any = ..., name: Any = ...) -> Any: ...
def normalize(tensor: Any, ord: Any = ..., axis: Any = ..., name: Any = ...) -> Any: ...
def pinv(a: Any, rcond: Any = ..., validate_args: Any = ..., name: Any = ...) -> Any: ...
def qr(input: Any, full_matrices: Any = ..., name: Any = ...) -> Any: ...
def set_diag(input: Any, diagonal: Any, name: Any = ..., **kwargs: Any) -> Any: ...
def slogdet(input: Any, name: Any = ...) -> Any: ...
def solve(matrix: Any, rhs: Any, adjoint: Any = ..., name: Any = ...) -> Any: ...
def sqrtm(input: Any, name: Any = ...) -> Any: ...
def svd(tensor: Any, full_matrices: Any = ..., compute_uv: Any = ..., name: Any = ...) -> Any: ...
def tensor_diag(diagonal: Any, name: Any = ...) -> Any: ...
def tensor_diag_part(input: Any, name: Any = ...) -> Any: ...
def trace(x: Any, name: Any = ...) -> Any: ...
def triangular_solve(matrix: Any, rhs: Any, lower: Any = ..., adjoint: Any = ..., name: Any = ...) -> Any: ...
def tridiagonal_matmul(diagonals: Any, rhs: Any, diagonals_format: Any = ..., name: Any = ...) -> Any: ...
def tridiagonal_solve(diagonals: Any, rhs: Any, diagonals_format: Any = ..., transpose_rhs: Any = ..., conjugate_rhs: Any = ..., name: Any = ..., partial_pivoting: Any = ..., perturb_singular: Any = ...) -> Any: ...

class LinearOperator: ...
class LinearOperatorAdjoint: ...
class LinearOperatorBlockDiag: ...
class LinearOperatorBlockLowerTriangular: ...
class LinearOperatorCirculant: ...
class LinearOperatorComposition: ...
class LinearOperatorDiag: ...
class LinearOperatorFullMatrix: ...
class LinearOperatorHouseholder: ...
class LinearOperatorIdentity: ...
class LinearOperatorInversion: ...
class LinearOperatorKronecker: ...
class LinearOperatorLowRankUpdate: ...
class LinearOperatorLowerTriangular: ...
class LinearOperatorPermutation: ...
class LinearOperatorScaledIdentity: ...
class LinearOperatorToeplitz: ...
class LinearOperatorTridiag: ...
class LinearOperatorZeros: ...

def __getattr__(name: str) -> Any: ...
