"""Type stubs for tensorflow.io module - provided by LegacyKerasPatch."""

from typing import Any

from . import gfile as gfile

from tensorflow.python.ops.parsing_config import FixedLenFeature as FixedLenFeature
from tensorflow.python.ops.parsing_config import FixedLenSequenceFeature as FixedLenSequenceFeature
from tensorflow.python.ops.parsing_config import VarLenFeature as VarLenFeature
from tensorflow.python.ops.parsing_config import RaggedFeature as RaggedFeature
from tensorflow.python.ops.parsing_config import SparseFeature as SparseFeature

from tensorflow.python.lib.io.tf_record import TFRecordCompressionType as TFRecordCompressionType
from tensorflow.python.lib.io.tf_record import TFRecordOptions as TFRecordOptions
from tensorflow.python.lib.io.tf_record import TFRecordWriter as TFRecordWriter

def decode_base64(input: Any, name: Any = ...) -> Any: ...
def decode_compressed(bytes: Any, compression_type: Any = ..., name: Any = ...) -> Any: ...
def decode_csv(records: Any, record_defaults: Any, field_delim: Any = ..., use_quote_delim: Any = ..., na_value: Any = ..., select_cols: Any = ..., name: Any = ...) -> Any: ...
def decode_image(contents: Any, channels: Any = ..., dtype: Any = ..., name: Any = ..., expand_animations: Any = ...) -> Any: ...
def decode_json_example(json_examples: Any, name: Any = ...) -> Any: ...
def decode_proto(bytes: Any, message_type: Any, field_names: Any, output_types: Any, descriptor_source: Any = ..., message_format: Any = ..., sanitize: Any = ..., name: Any = ...) -> Any: ...
def decode_raw(input_bytes: Any, out_type: Any, little_endian: Any = ..., fixed_length: Any = ..., name: Any = ...) -> Any: ...
def deserialize_many_sparse(serialized_sparse: Any, dtype: Any, rank: Any = ..., name: Any = ...) -> Any: ...
def encode_base64(input: Any, pad: Any = ..., name: Any = ...) -> Any: ...
def encode_proto(sizes: Any, values: Any, message_type: Any, field_names: Any, descriptor_source: Any = ..., name: Any = ...) -> Any: ...
def extract_jpeg_shape(contents: Any, output_type: Any = ..., name: Any = ...) -> Any: ...
def matching_files(pattern: Any, name: Any = ...) -> Any: ...
def match_filenames_once(pattern: Any, name: Any = ...) -> Any: ...
def parse_example(serialized: Any, features: Any, example_names: Any = ..., name: Any = ...) -> Any: ...
def parse_sequence_example(serialized: Any, context_features: Any = ..., sequence_features: Any = ..., example_names: Any = ..., name: Any = ...) -> Any: ...
def parse_single_example(serialized: Any, features: Any, example_names: Any = ..., name: Any = ...) -> Any: ...
def parse_single_sequence_example(serialized: Any, context_features: Any = ..., sequence_features: Any = ..., example_name: Any = ..., name: Any = ...) -> Any: ...
def parse_tensor(serialized: Any, out_type: Any, name: Any = ...) -> Any: ...
def read_file(filename: Any, name: Any = ...) -> Any: ...
def serialize_many_sparse(sp_input: Any, out_type: Any = ..., name: Any = ...) -> Any: ...
def serialize_sparse(sp_input: Any, out_type: Any = ..., name: Any = ...) -> Any: ...
def serialize_tensor(tensor: Any, name: Any = ...) -> Any: ...
def write_file(filename: Any, contents: Any, name: Any = ...) -> Any: ...
def write_graph(graph_or_graph_def: Any, logdir: Any, name: Any, as_text: Any = ...) -> Any: ...

def __getattr__(name: str) -> Any: ...
