from typing import Any


def image_dataset_from_directory(*args: Any, **kwargs: Any) -> Any: ...
def text_dataset_from_directory(*args: Any, **kwargs: Any) -> Any: ...
def timeseries_dataset_from_array(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
