from typing import Any


class Constraint: ...
class MaxNorm: ...
class MinMaxNorm: ...
class NonNeg: ...
class UnitNorm: ...
class max_norm: ...
class min_max_norm: ...
class non_neg: ...
class unit_norm: ...

def deserialize(*args: Any, **kwargs: Any) -> Any: ...
def get(*args: Any, **kwargs: Any) -> Any: ...
def serialize(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
