from typing import Any

from legacy_keras_patch.distribution import LayoutMap as LayoutMap

class DataParallel: ...
class DeviceMesh: ...
class ModelParallel: ...
class TensorLayout: ...

def distribute_tensor(*args: Any, **kwargs: Any) -> Any: ...
def distribution(*args: Any, **kwargs: Any) -> Any: ...
def get_device_count(*args: Any, **kwargs: Any) -> Any: ...
def initialize(*args: Any, **kwargs: Any) -> Any: ...
def list_devices(*args: Any, **kwargs: Any) -> Any: ...
def set_distribution(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
